/*
 Highcharts Dashboards v1.0.2 (2023-08-10)

 (c) 2009-2023 Highsoft AS

 License: www.highcharts.com/license
*/
'use strict';var r=r||{};r.scope={};r.ASSUME_ES5=!1;r.ASSUME_NO_NATIVE_MAP=!1;r.ASSUME_NO_NATIVE_SET=!1;r.SIMPLE_FROUND_POLYFILL=!1;r.ISOLATE_POLYFILLS=!1;r.defineProperty=r.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,g,k){if(b==Array.prototype||b==Object.prototype)return b;b[g]=k.value;return b};
r.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var g=0;g<b.length;++g){var k=b[g];if(k&&k.Math==Math)return k}throw Error("Cannot find global object");};r.global=r.getGlobal(this);r.polyfills={};r.propertyToPolyfillSymbol={};r.POLYFILL_PREFIX="$jscp$";r.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
r.polyfill=function(b,g,k,d){g&&(r.ISOLATE_POLYFILLS?r.polyfillIsolated(b,g,k,d):r.polyfillUnisolated(b,g,k,d))};r.polyfillUnisolated=function(b,g){var k=r.global;b=b.split(".");for(var d=0;d<b.length-1;d++){var f=b[d];f in k||(k[f]={});k=k[f]}b=b[b.length-1];d=k[b];g=g(d);g!=d&&null!=g&&r.defineProperty(k,b,{configurable:!0,writable:!0,value:g})};
r.polyfillIsolated=function(b,g,k){var d=b.split(".");b=1===d.length;var f=d[0];f=!b&&f in r.polyfills?r.polyfills:r.global;for(var x=0;x<d.length-1;x++){var y=d[x];y in f||(f[y]={});f=f[y]}d=d[d.length-1];k=r.IS_SYMBOL_NATIVE&&"es6"===k?f[d]:null;g=g(k);null!=g&&(b?r.defineProperty(r.polyfills,d,{configurable:!0,writable:!0,value:g}):g!==k&&(r.propertyToPolyfillSymbol[d]=r.IS_SYMBOL_NATIVE?r.global.Symbol(d):r.POLYFILL_PREFIX+d,d=r.propertyToPolyfillSymbol[d],r.defineProperty(f,d,{configurable:!0,
writable:!0,value:g})))};r.polyfill("Array.prototype.includes",function(b){return b?b:function(b,k){var d=this;d instanceof String&&(d=String(d));var f=d.length;k=k||0;for(0>k&&(k=Math.max(k+f,0));k<f;k++){var x=d[k];if(x===b||Object.is(x,b))return!0}return!1}},"es7","es3");
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("dashboards/modules/dashboards-plugin",["dashboards"],function(g){b(g);b.Dashboards=g;return b}):b("undefined"!==typeof Dashboards?Dashboards:void 0)})(function(b){function g(b,d,f,x){b.hasOwnProperty(d)||(b[d]=x.apply(null,f),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("DashboardsModuleLoaded",{detail:{path:d,module:b[d]}})))}b=b?b._modules:
{};g(b,"Dashboards/Plugins/DataGridSyncHandlers.js",[b["Core/Utilities.js"]],function(b){const {addEvent:d}=b;return{highlight:{emitter:["highlightEmitter",function(){if("DataGrid"===this.type){const {dataGrid:f,board:b}=this;if(b){const {dataCursor:y}=b,l=[];if(f)return l.push(d(f.container,"dataGridHover",a=>{const t=this.connector&&this.connector.table;if(t){a=a.row;const c=a.querySelector(`.highcharts-datagrid-cell[data-original-data="${a.dataset.rowXIndex}"]`);y.emitCursor(t,{type:"position",
row:parseInt(a.dataset.rowIndex,10),column:c?c.dataset.columnName:void 0,state:"dataGrid.hoverRow"})}})),l.push(d(f.container,"mouseout",()=>{const a=this.connector&&this.connector.table;a&&y.emitCursor(a,{type:"position",state:"dataGrid.hoverOut"})})),function(){l.forEach(a=>a())}}}}],handler:["highlightHandler",void 0,function(){const {board:f}=this,b=a=>{a=a.cursor;if("position"===a.type){var {row:c}=a;({dataGrid:a}=this);void 0!==c&&a&&(c=a.container.querySelector(`.highcharts-datagrid-row[data-row-index="${c}"]`))&&
(a.toggleRowHighlight(c),a.hoveredRow=c)}},d=()=>{const {dataGrid:a}=this;a&&a.toggleRowHighlight(void 0)},l=()=>{const {dataCursor:a}=f;if(a){var c=this.connector&&this.connector.table;c&&(a.addListener(c.id,"point.mouseOver",b),a.addListener(c.id,"point.mouseOut",d))}},a=()=>{const a=f.dataCursor,c=this.connector&&this.connector.table;c&&(a.addListener(c.id,"point.mouseOver",b),a.addListener(c.id,"point.mouseOut",d))};f&&(l(),this.on("setConnector",()=>a()),this.on("afterSetConnector",()=>l()))}]},
extremes:{handler:function(){const {board:b}=this,d=a=>{"position"===a.cursor.type&&this.dataGrid&&a.cursors.length&&(a=a.cursors[a.cursors.length-1],"row"in a&&"number"===typeof a.row&&({row:a}=a,this.dataGrid.scrollToRow(a)))},k=()=>{const {dataCursor:a}=b;if(a){var f=this.connector&&this.connector.table;f&&a.addListener(f.id,"xAxis.extremes.min",d)}},l=()=>{const a=this.connector&&this.connector.table,{dataCursor:f}=b;a&&f.removeListener(a.id,"xAxis.extremes.min",d)};b&&(k(),this.on("setConnector",
()=>l()),this.on("afterSetConnector",()=>k()))}},visibility:{handler:function(){const b=this,{board:d}=b,k=a=>{a=a.cursor;const c=b.dataGrid;c&&"position"===a.type&&a.column&&c.update({columns:{[a.column]:{show:"series.hide"!==a.state}}})},l=()=>{const {dataCursor:a}=d;if(a){var c=this.connector&&this.connector.table;c&&(a.addListener(c.id,"series.show",k),a.addListener(c.id,"series.hide",k))}},a=()=>{const a=this.connector&&this.connector.table,{dataCursor:c}=d;a&&(c.removeListener(a.id,"series.show",
k),c.removeListener(a.id,"series.hide",k))};d&&(l(),this.on("setConnector",()=>a()),this.on("afterSetConnector",()=>l()))}}}});g(b,"Dashboards/Plugins/DataGridComponent.js",[b["Dashboards/Components/Component.js"],b["Data/Converters/DataConverter.js"],b["Dashboards/Plugins/DataGridSyncHandlers.js"],b["Core/Utilities.js"]],function(b,d,f,x){var k=this&&this.__awaiter||function(a,b,c,f){function e(a){return a instanceof c?a:new c(function(e){e(a)})}return new (c||(c=Promise))(function(c,m){function h(h){try{B(f.next(h))}catch(C){m(C)}}
function w(h){try{B(f["throw"](h))}catch(C){m(C)}}function B(a){a.done?c(a.value):e(a.value).then(h,w)}B((f=f.apply(a,b||[])).next())})};const {diffObjects:l,merge:a,uniqueKey:t}=x;class c extends b{static onUpdate(a,c){if(a=a.target){var e=a.closest(".highcharts-datagrid-row"),b=a.closest(".highcharts-datagrid-cell");const f=new d;e&&e instanceof HTMLElement&&b&&b instanceof HTMLElement&&(e=e.dataset.rowIndex,{columnName:b}=b.dataset,void 0!==e&&void 0!==b&&(c=c.table))&&(a=f.asGuessedType(a.value),
a instanceof Date&&(a=a.toString()),c.setCell(b,parseInt(e,10),a))}}static fromJSON(e,b){const f=e.options,u=JSON.parse(e.options.dataGridOptions||"");b=new c(b,a(f,{dataGridOptions:u,syncHandlers:c.syncHandlers}));b.emit({type:"fromJSON",json:e});return b}constructor(e,u){u=a(c.defaultOptions,u);super(e,u);this.connectorListeners=[];this.options=u;this.type="DataGrid";this.options.dataGridClassName&&this.contentElement.classList.add(this.options.dataGridClassName);this.options.dataGridID&&(this.contentElement.id=
this.options.dataGridID);this.filterAndAssignSyncOptions(f);this.sync=new c.Sync(this,this.syncHandlers);this.dataGridOptions=this.options.dataGridOptions||{};this.innerResizeTimeouts=[];this.on("afterSetConnector",a=>{this.disableEditingModifiedColumns(a.connector)});this.on("tableChanged",()=>{var a;this.dataGrid&&this.dataGrid.cellInputEl||(null===(a=this.dataGrid)||void 0===a?void 0:a.update({dataTable:this.filterColumns()}))});b.addInstance(this)}disableEditingModifiedColumns(a){var e;if((a=
a.options.dataModifier)&&"Math"===a.type&&(a=a.columnFormulas)){var b={};for(let e=0,c=a.length;e<c;++e)b[a[e].column]={editable:!1};null===(e=this.dataGrid)||void 0===e?void 0:e.update({columns:b})}}load(){this.emit({type:"load"});super.load();this.parentElement.appendChild(this.element);this.hasLoaded=!0;if(this.connector&&!this.connectorListeners.length){const a=this.connectorListeners;a.push(this.connector.on("afterLoad",a=>{a.table&&this.connector&&this.connector.table.setColumns(a.table.getColumns())}));
a.push(this.connector.table.on("afterSetCell",a=>{var e=this.dataGrid;let b=!0;if(e){e=e.rowElements[a.rowIndex];let c=[];e&&(c=Array.prototype.slice.call(e.childNodes));c.forEach(e=>{if(0<e.childElementCount){var c=e.childNodes[0];c="string"===typeof a.cellValue?c.value:+c.value;e.dataset.columnName===a.columnName&&c===a.cellValue&&(b=!1)}})}b?this.update({}):void 0}))}this.emit({type:"afterLoad"});return this}render(){this.emit({type:"beforeRender"});super.render();this.dataGrid||(this.dataGrid=
this.constructDataGrid());this.connector&&this.dataGrid&&this.dataGrid.dataTable.modified!==this.connector.table.modified&&this.dataGrid.update({dataTable:this.filterColumns()});this.sync.start();this.emit({type:"afterRender"});this.setupConnectorUpdate();return this}redraw(){super.redraw();return this.render()}resize(a,b){this.dataGrid&&(super.resize(a,b),this.dataGrid.setSize(a,b))}update(a){const e=Object.create(null,{update:{get:()=>super.update}});var b;return k(this,void 0,void 0,function*(){if((null===
(b=a.connector)||void 0===b?void 0:b.id)!==this.connectorId){const a=this.connectorListeners;for(let e=0,b=a.length;e<b;++e)a[e]();a.length=0}yield e.update.call(this,a);this.dataGrid&&(this.filterAndAssignSyncOptions(f),this.dataGrid.update(this.options.dataGridOptions||{}));this.emit({type:"afterUpdate"})})}constructDataGrid(){if(c.DataGridConstructor)return this.dataGrid=new c.DataGridConstructor(this.contentElement,Object.assign(Object.assign({},this.options.dataGridOptions),{dataTable:this.connector&&
this.connector.table.modified}));throw Error("DataGrid not connected.");}setupConnectorUpdate(){const {connector:a,dataGrid:b}=this;if(a&&b)b.on("cellClick",e=>{"input"in e&&e.input.addEventListener("keyup",e=>this.options.onUpdate(e,a))})}filterColumns(){var a,b=null===(a=this.connector)||void 0===a?void 0:a.table.modified;const c=this.options.visibleColumns;if(b){if(null===c||void 0===c||!c.length)return b;a=b.getColumnNames().filter(a=>0<(null===c||void 0===c?void 0:c.length)&&!c.includes(a));
b=b.clone();b.deleteColumns(a);return b}}toJSON(){var a=JSON.stringify(this.options.dataGridOptions);const b=super.toJSON();a=Object.assign(Object.assign({},b),{options:Object.assign(Object.assign({},b.options),{dataGridOptions:a})});this.emit({type:"toJSON",json:a});return a}getOptions(){return Object.assign(Object.assign({},l(this.options,c.defaultOptions)),{type:"DataGrid"})}}c.syncHandlers=f;c.defaultOptions=a(b.defaultOptions,{dataGridClassName:"dataGrid-container",dataGridID:"dataGrid-"+t(),
dataGridOptions:{},editableOptions:[{name:"connectorName",propertyPath:["connector","id"],type:"select"}],syncHandlers:f,onUpdate:c.onUpdate});return c});g(b,"Dashboards/Plugins/DataGridPlugin.js",[b["Dashboards/Plugins/DataGridComponent.js"]],function(b){return{custom:{connectDataGrid:function(d){b.DataGridConstructor=d}},name:"DataGrid.DashboardsPlugin",onRegister:function(d){({ComponentRegistry:d}=d);d.registerComponent("DataGrid",b)},onUnregister:function(){}}});g(b,"Dashboards/Plugins/HighchartsSyncHandlers.js",
[b["Core/Utilities.js"]],function(b){const {addEvent:d}=b;return{extremes:{emitter:function(){if("Highcharts"===this.type){const b=this,k=[];this.on("afterRender",()=>{const {chart:f,connector:l,board:a}=b,t=l&&l.table,{dataCursor:c}=a;if(t&&f){const a=a=>{var b=!!a.resetSelection;if((!a.trigger||a.trigger&&"dashboards-sync"!==a.trigger)&&!b){var e=a.target;const h=e.series.filter(a=>t.hasColumns([a.name])),[w]=h.length?h:e.series;if(w){b=w.points.filter(a=>a.isInside||!1);const f={type:"position",
state:`${e.coll}.extremes.min`},m={type:"position",state:`${e.coll}.extremes.max`};h.length&&"xAxis"===e.coll&&b.length&&(e=e.dateTime&&t.hasColumns(["x"])?"x":w.name,f.row=b[0].index,f.column=e,m.row=b[b.length-1].index,m.column=e);c.emitCursor(t,f,a,!0).emitCursor(t,m,a,!0)}}},b=()=>f.axes.map(b=>d(b,"afterSetExtremes",a));let l=b();const y=()=>{l.forEach(a=>{a()});l=[]};k.push(d(f,"selection",a=>{a.resetSelection&&(y(),c.emitCursor(t,{type:"position",state:"chart.zoomOut"},a),l.push(...b()))}));
k.push(()=>{c.remitCursor(t.id,{type:"position",state:"xAxis.extremes.min"});c.remitCursor(t.id,{type:"position",state:"xAxis.extremes.max"});y()})}});return function(){k.forEach(b=>b())}}},handler:function(){const {chart:b,board:d}=this;b&&d&&["xAxis","yAxis"].forEach(f=>{const l=[],a=a=>{const {cursor:e,event:c}=a;if("position"===e.type){const a=c&&c.target;if(a&&b){let e=!1;b[f].forEach(b=>{a.coll===b.coll&&a!==b&&null!==a.min&&null!==a.max&&b.max!==a.max&&b.min!==a.min&&(b.setExtremes(a.min,a.max,
!1,void 0,{trigger:"dashboards-sync"}),e=!0)});e&&!b.resetZoomButton&&b.showResetZoom();b.redraw()}}},k=()=>{const {dataCursor:e}=d,{connector:c}=this;if(c){const {table:d}=c;e.addListener(d.id,`${f}.extremes.min`,a);e.addListener(d.id,`${f}.extremes.max`,a);const k=()=>{b.zoomOut();setTimeout(()=>{this.element.querySelectorAll(".highcharts-reset-zoom").forEach(a=>{a.remove()})})};e.addListener(d.id,"chart.zoomOut",k);l.push(()=>{e.removeListener(d.id,`${f}.extremes.min`,a);e.removeListener(d.id,
`${f}.extremes.max`,a);e.removeListener(d.id,"chart.zoomOut",k)})}},c=()=>{l.forEach(a=>a())};d&&(k(),this.on("setConnector",()=>c()),this.on("afterSetConnector",()=>k()))})}},highlight:{emitter:["highlightEmitter",function(){if("Highcharts"===this.type){const {chart:b,board:d}=this;if(d){const {dataCursor:f}=d;this.on("afterRender",()=>{const d=this.connector&&this.connector.table;b&&b.series&&d&&b.series.forEach(a=>{a.update({point:{events:{mouseOver:function(){let b=0;const c=d.getModifier();c&&
"getModifiedTableOffset"in c&&(b=c.getModifiedTableOffset(d));f.emitCursor(d,{type:"position",row:b+this.index,column:a.name,state:"point.mouseOver"})},mouseOut:function(){let b=0;const c=d.getModifier();c&&"getModifiedTableOffset"in c&&(b=c.getModifiedTableOffset(d));f.emitCursor(d,{type:"position",row:b+this.index,column:a.name,state:"point.mouseOut"})}}}})})});return function(){b&&b.series&&b.series.forEach(b=>{b.update({point:{events:{mouseOver:void 0,mouseOut:void 0}}})})}}}}],handler:function(){const {chart:b,
board:d}=this,k=a=>{const e=this.connector&&this.connector.table;if(e){var c=0,d=e.getModifier();d&&"getModifiedTableOffset"in d&&(c=d.getModifiedTableOffset(e));if(b&&b.series.length){const e=a.cursor;"position"===e.type&&([a]=1<b.series.length&&e.column?b.series.filter(a=>a.name===e.column):b.series,a&&a.visible&&void 0!==e.row&&(c=a.points[e.row-c])&&b.tooltip&&b.tooltip.refresh(c))}}},l=()=>{b&&b.series.length&&b.tooltip&&b.tooltip.hide()},a=()=>{const {dataCursor:a}=d;if(a){const b=this.connector&&
this.connector.table;b&&(a.addListener(b.id,"point.mouseOver",k),a.addListener(b.id,"dataGrid.hoverRow",k),a.addListener(b.id,"point.mouseOut",l),a.addListener(b.id,"dataGrid.hoverOut",l))}},t=()=>{const a=this.connector&&this.connector.table;a&&(d.dataCursor.removeListener(a.id,"point.mouseOver",k),d.dataCursor.removeListener(a.id,"dataGrid.hoverRow",k),d.dataCursor.removeListener(a.id,"point.mouseOut",l),d.dataCursor.removeListener(a.id,"dataGrid.hoverOut",l))};d&&(a(),this.on("setConnector",()=>
t()),this.on("afterSetConnector",()=>a()))}},visibility:{emitter:function(){if("Highcharts"===this.type){const b=this;return this.on("afterRender",()=>{const {chart:d,connector:f,board:k}=b,a=f&&f.table;if(a&&k&&d){const {dataCursor:b}=k,{series:c}=d;c.forEach(e=>{e.update({events:{show:function(){b.emitCursor(a,{type:"position",state:"series.show",column:this.name})},hide:function(){b.emitCursor(a,{type:"position",state:"series.hide",column:this.name})}}})})}})}},handler:function(){const b=this,
{board:d}=this,k=(a,b)=>{for(const e of a)if(e.name===b)return e},l=a=>{const e=b.chart;e&&"position"===a.cursor.type&&void 0!==a.cursor.column&&(a=k(e.series,a.cursor.column))&&a.setVisible(!0,!0)},a=a=>{const e=b.chart;e&&"position"===a.cursor.type&&void 0!==a.cursor.column&&(a=k(e.series,a.cursor.column))&&a.setVisible(!1,!0)},t=()=>{const {dataCursor:b}=d;if(b){var c=this.connector&&this.connector.table;c&&(b.addListener(c.id,"series.show",l),b.addListener(c.id,"series.hide",a))}},c=()=>{const b=
this.connector&&this.connector.table;b&&(d.dataCursor.removeListener(b.id,"series.show",l),d.dataCursor.removeListener(b.id,"series.hide",a))};d&&(t(),this.on("setConnector",()=>c()),this.on("afterSetConnector",()=>t()))}}}});g(b,"Dashboards/Plugins/HighchartsComponent.js",[b["Dashboards/Components/Component.js"],b["Data/Converters/DataConverter.js"],b["Data/DataTable.js"],b["Dashboards/Globals.js"],b["Dashboards/Plugins/HighchartsSyncHandlers.js"],b["Core/Utilities.js"]],function(b,d,f,g,y,l){var a=
this&&this.__awaiter||function(a,b,c,e){function h(a){return a instanceof c?a:new c(function(b){b(a)})}return new (c||(c=Promise))(function(c,d){function w(a){try{C(e.next(a))}catch(q){d(q)}}function m(a){try{C(e["throw"](a))}catch(q){d(q)}}function C(a){a.done?c(a.value):h(a.value).then(w,m)}C((e=e.apply(a,b||[])).next())})};const {addEvent:k,createElement:c,merge:e,splat:u,uniqueKey:x,error:p,diffObjects:A,defined:n}=l;class m extends b{static fromJSON(a,b){const h=a.options,c=JSON.parse(a.options.chartOptions||
"{}");b=new m(b,e(h,{chartOptions:c,syncHandlers:m.syncHandlers}));b.emit({type:"fromJSON",json:a});return b}constructor(a,d){d=e(m.defaultOptions,d);super(a,d);this.options=d;this.chartConstructor=this.options.chartConstructor;this.type="Highcharts";this.chartContainer=c("figure",void 0,void 0,void 0,!0);this.setOptions();this.sync=new m.Sync(this,this.syncHandlers);this.chartOptions=e(this.options.chartOptions||{chart:{}},{tooltip:{}});this.on("tableChanged",()=>this.updateSeries());if(this.connector)this.connector.on("afterLoad",
a=>{a.table&&this.connector&&this.connector.table.setColumns(a.table.getColumns())});this.innerResizeTimeouts=[];b.addInstance(this)}load(){this.emit({type:"load"});super.load();this.parentElement.appendChild(this.element);this.contentElement.appendChild(this.chartContainer);this.hasLoaded=!0;this.emit({type:"afterLoad"});return this}render(){this.emit({type:"beforeRender"});super.render();this.chart=this.getChart();this.updateSeries();this.sync.start();this.emit({type:"afterRender"});this.setupConnectorUpdate();
return this}resize(a,b){for(super.resize(a,b);this.innerResizeTimeouts.length;)(a=this.innerResizeTimeouts.pop())&&clearTimeout(a);this.innerResizeTimeouts.push(setTimeout(()=>{this.chart&&this.chart.setSize(null,this.contentElement.clientHeight,!1)},33));return this}setupConnectorUpdate(){const {connector:a,chart:b}=this;a&&b&&this.options.allowConnectorUpdate&&b.series.forEach(b=>{b.points.forEach(b=>{k(b,"drag",()=>{this.onChartUpdate(b,a)})})})}setOptions(){this.options.chartClassName&&this.chartContainer.classList.add(this.options.chartClassName);
this.options.chartID&&(this.chartContainer.id=this.options.chartID);this.filterAndAssignSyncOptions(y)}onChartUpdate(a,b){b=b.table;const h=a.series.name,c=a.index;a=(new d).asNumber(a.y);b.setCell(h,c,a)}update(b,c=!0){const h=Object.create(null,{update:{get:()=>super.update}});return a(this,void 0,void 0,function*(){yield h.update.call(this,b,!1);this.setOptions();this.chart&&this.chart.update(e(this.options.chartOptions)||{});this.emit({type:"afterUpdate"});c&&this.redraw()})}updateSeries(){var a;
if(this.chart&&this.connector){this.presentationTable=this.presentationModifier?this.connector.table.modified.clone():this.connector.table;const {id:b}=this.connector.table,{chart:c}=this,h=this.options.columnAssignment||{},e={};this.presentationModifier&&(this.presentationTable=this.presentationModifier.modifyTable(this.presentationTable).modified);const d=this.presentationTable,m=null===(a=d.getModifier())||void 0===a?void 0:a.options;this.emit({type:"afterPresentationModifier",table:d});const k=
d.modified.getColumnNames().filter(a=>{const b=this.activeGroup?!1!==this.activeGroup.getSharedState().getColumnVisibility(a):!0;return n(this.options.columnAssignment)?b&&h[a]?"x"===h[a]?(e[a]=a,!1):!0:!1:!0});k.map((a,h)=>{for(var e,d=0;d<c.series.length;){const a=c.series[d],e=a.options.id===`${b}-series-${h}`,m=-1!==k.indexOf(a.name);d++;if(m&&e)return a;!m&&e&&a.destroy()}d=!("Math"===(null===m||void 0===m?void 0:m.type)&&(null===(e=m.columnFormulas)||void 0===e?0:e.some(b=>b.column===a)));return c.addSeries({name:a,
id:`${b}-series-${h}`,dragDrop:{draggableY:d}},!1)}).forEach(a=>{var b=Object.keys(e)[0];const c=new f({columns:d.modified.getColumns([b,a.name])});c.renameColumn(a.name,"y");b&&c.renameColumn(b,"x");b=c.getRowObjects().reduce((a,b)=>{a.push([b.x,b.y]);return a},[]);a.setData(b)})}}getChart(){return this.chart||this.createChart()}createChart(){const a=m.charter||g.win.Highcharts;if("chart"!==this.chartConstructor){const b=a[this.chartConstructor];if(b)try{return b(this.chartContainer,this.chartOptions)}catch(B){p("The Highcharts component is misconfigured: `"+
this.cell.id+"`")}}if("function"!==typeof a.chart)throw Error("Chart constructor not found");return this.chart=a.chart(this.chartContainer,this.chartOptions)}registerChartEvents(){if(this.chart&&this.chart.options){const a=this.chart.options;"chart series yAxis xAxis colorAxis annotations navigation".split(" ").map(b=>{let c=a[b]||{};!Array.isArray(c)&&c.events&&(c=[c]);return c&&"object"===typeof c&&Array.isArray(c)?c.reduce((a,c,e)=>{c&&c.events&&(a[c.id||`${b}-${e}`]=c.events);return a},{})||{}:
{}}).forEach(a=>{Object.keys(a).forEach(b=>{const c=a[b];Object.keys(c).forEach(a=>{this.callbackRegistry.addCallback(`${b}-${a}`,{type:"seriesEvent",func:c[a]})})})})}}setConnector(a){var b;const c=this.chart;if(this.connector&&c&&c.series&&this.connector.table.id!==(null===a||void 0===a?void 0:a.table.id)){const a=this.connector.table.id;for(let e=c.series.length-1;0<=e;e--){const d=c.series[e];-1!==(null===(b=d.options.id)||void 0===b?void 0:b.indexOf(a))&&d.remove(!1)}}super.setConnector(a);return this}toJSON(){var a=
JSON.stringify(this.options.chartOptions);const b=this.options.chartConstructor;this.registerChartEvents();const c=super.toJSON();a=Object.assign(Object.assign({},c),{type:"Highcharts",options:Object.assign(Object.assign({},c.options),{chartOptions:a,chartConstructor:b,type:"Highcharts",sync:{}})});this.emit({type:"toJSON",json:a});return a}getOptions(){return Object.assign(Object.assign({},A(this.options,m.defaultOptions)),{type:"Highcharts"})}getEditableOptions(){var a;const b=this.options,c=this.chart,
d=c&&c.options,m=d&&(null===(a=d.chart)||void 0===a?void 0:a.type)||"line";return e(b,{chartOptions:d},{chartOptions:{yAxis:u(c&&c.yAxis[0].options),xAxis:u(c&&c.xAxis[0].options),plotOptions:{series:(d&&d.plotOptions||{})[m]}}})}getEditableOptionValue(a){if(a)return 1===a.length&&"chartOptions"===a[0]?JSON.stringify(this.options.chartOptions,null,2):super.getEditableOptionValue.call(this,a)}}m.syncHandlers=y;m.defaultOptions=e(b.defaultOptions,{allowConnectorUpdate:!0,chartClassName:"chart-container",
chartID:"chart-"+x(),chartOptions:{chart:{styledMode:!0},series:[]},chartConstructor:"",editableOptions:(b.defaultOptions.editableOptions||[]).concat([{name:"chartOptions",type:"nested",nestedOptions:[{name:"chart",options:[{name:"title",propertyPath:["chartOptions","title","text"],type:"input"},{name:"subtitle",propertyPath:["chartOptions","subtitle","text"],type:"input"},{name:"type",propertyPath:["chartOptions","chart","type"],type:"select",selectOptions:[{name:"column",iconURL:"series-types/icon-column.svg"},
{name:"line",iconURL:"series-types/icon-line.svg"},{name:"scatter",iconURL:"series-types/icon-scatter.svg"},{name:"pie",iconURL:"series-types/icon-pie.svg"}]}]},{name:"xAxis",options:[{name:"title",propertyPath:["chartOptions","xAxis","title","text"],type:"input"},{name:"type",propertyPath:["chartOptions","xAxis","type"],type:"select",selectOptions:[{name:"linear"},{name:"datetime"},{name:"logarithmic"}]}]},{name:"yAxis",options:[{name:"title",propertyPath:["chartOptions","yAxis","title","text"],
type:"input"},{name:"type",propertyPath:["chartOptions","yAxis","type"],type:"select",selectOptions:[{name:"linear"},{name:"datetime"},{name:"logarithmic"}]}]},{name:"legend",showToggle:!0,propertyPath:["chartOptions","legend","enabled"],options:[{name:"align",propertyPath:["chartOptions","legend","align"],type:"select",selectOptions:[{name:"left"},{name:"center"},{name:"right"}]}]},{name:"tooltip",showToggle:!0,propertyPath:["chartOptions","tooltip","enabled"],options:[{name:"split",propertyPath:["chartOptions",
"tooltip","split"],type:"toggle"}]},{name:"dataLabels",propertyPath:["chartOptions","plotOptions","series","dataLabels","enabled"],showToggle:!0,options:[{name:"align",propertyPath:["chartOptions","plotOptions","series","dataLabels","align"],type:"select",selectOptions:[{name:"left"},{name:"center"},{name:"right"}]}]},{name:"credits",showToggle:!0,propertyPath:["chartOptions","credits","enabled"],options:[{name:"name",propertyPath:["chartOptions","credits","text"],type:"input"},{name:"url",propertyPath:["chartOptions",
"credits","href"],type:"input"}]}]},{name:"chartConfig",propertyPath:["chartOptions"],type:"textarea"},{name:"chartClassName",propertyPath:["chartClassName"],type:"input"},{name:"chartID",propertyPath:["chartID"],type:"input"}]),syncHandlers:y,editableOptionsBindings:e(b.defaultOptions.editableOptionsBindings,{skipRedraw:["chartOptions","chartConfig"]}),columnAssignment:void 0});return m});g(b,"Core/Chart/ChartDefaults.js",[],function(){return{alignThresholds:!1,panning:{enabled:!1,type:"x"},styledMode:!1,
borderRadius:0,colorCount:10,allowMutatingData:!0,ignoreHiddenSeries:!0,spacing:[10,10,15,10],resetZoomButton:{theme:{zIndex:6},position:{align:"right",x:-10,y:10}},reflow:!0,type:"line",zooming:{singleTouch:!1,resetButton:{theme:{zIndex:6},position:{align:"right",x:-10,y:10}}},width:null,height:null,borderColor:"#334eff",backgroundColor:"#ffffff",plotBorderColor:"#cccccc"}});g(b,"Core/Color/Color.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,d){const {isNumber:f,merge:k,pInt:g}=d;
class l{static parse(a){return a?new l(a):l.None}constructor(a){this.rgba=[NaN,NaN,NaN,NaN];this.input=a;const d=b.Color;if(d&&d!==l)return new d(a);this.init(a)}init(a){let b;let c;if("object"===typeof a&&"undefined"!==typeof a.stops)this.stops=a.stops.map(a=>new l(a[1]));else if("string"===typeof a){this.input=a=l.names[a.toLowerCase()]||a;if("#"===a.charAt(0)){var d=a.length;var f=parseInt(a.substr(1),16);7===d?b=[(f&16711680)>>16,(f&65280)>>8,f&255,1]:4===d&&(b=[(f&3840)>>4|(f&3840)>>8,(f&240)>>
4|f&240,(f&15)<<4|f&15,1])}if(!b)for(f=l.parsers.length;f--&&!b;)c=l.parsers[f],(d=c.regex.exec(a))&&(b=c.parse(d))}b&&(this.rgba=b)}get(a){const b=this.input,c=this.rgba;if("object"===typeof b&&"undefined"!==typeof this.stops){const c=k(b);c.stops=[].slice.call(c.stops);this.stops.forEach((b,d)=>{c.stops[d]=[c.stops[d][0],b.get(a)]});return c}return c&&f(c[0])?"rgb"===a||!a&&1===c[3]?"rgb("+c[0]+","+c[1]+","+c[2]+")":"a"===a?`${c[3]}`:"rgba("+c.join(",")+")":b}brighten(a){const b=this.rgba;if(this.stops)this.stops.forEach(function(b){b.brighten(a)});
else if(f(a)&&0!==a)for(let c=0;3>c;c++)b[c]+=g(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255);return this}setOpacity(a){this.rgba[3]=a;return this}tweenTo(a,b){const c=this.rgba,d=a.rgba;if(!f(c[0])||!f(d[0]))return a.input||"none";a=1!==d[3]||1!==c[3];return(a?"rgba(":"rgb(")+Math.round(d[0]+(c[0]-d[0])*(1-b))+","+Math.round(d[1]+(c[1]-d[1])*(1-b))+","+Math.round(d[2]+(c[2]-d[2])*(1-b))+(a?","+(d[3]+(c[3]-d[3])*(1-b)):"")+")"}}l.names={white:"#ffffff",black:"#000000"};l.parsers=[{regex:/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,
parse:function(a){return[g(a[1]),g(a[2]),g(a[3]),parseFloat(a[4],10)]}},{regex:/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,parse:function(a){return[g(a[1]),g(a[2]),g(a[3]),1]}}];l.None=new l("");"";return l});g(b,"Core/Color/Palettes.js",[],function(){return{colors:"#2caffe #544fc5 #00e272 #fe6a35 #6b8abc #d568fb #2ee0ca #fa4b42 #feb56a #91e8e1".split(" ")}});g(b,"Core/Time.js",[b["Core/Globals.js"],b["Core/Utilities.js"]],function(b,d){const {win:f}=b,{defined:k,error:g,extend:l,
isObject:a,merge:t,objectEach:c,pad:e,pick:u,splat:z,timeUnits:p}=d,A=b.isSafari&&f.Intl&&f.Intl.DateTimeFormat.prototype.formatRange,n=b.isSafari&&f.Intl&&!f.Intl.DateTimeFormat.prototype.formatRange;class m{constructor(a){this.options={};this.variableTimezone=this.useUTC=!1;this.Date=f.Date;this.getTimezoneOffset=this.timezoneOffsetFunction();this.update(a)}get(a,b){if(this.variableTimezone||this.timezoneOffset){const c=b.getTime(),d=c-this.getTimezoneOffset(b);b.setTime(d);a=b["getUTC"+a]();b.setTime(c);
return a}return this.useUTC?b["getUTC"+a]():b["get"+a]()}set(a,b,c){if(this.variableTimezone||this.timezoneOffset){if("Milliseconds"===a||"Seconds"===a||"Minutes"===a&&0===this.getTimezoneOffset(b)%36E5)return b["setUTC"+a](c);var d=this.getTimezoneOffset(b);d=b.getTime()-d;b.setTime(d);b["setUTC"+a](c);a=this.getTimezoneOffset(b);d=b.getTime()+a;return b.setTime(d)}return this.useUTC||A&&"FullYear"===a?b["setUTC"+a](c):b["set"+a](c)}update(a={}){const b=u(a.useUTC,!0);this.options=a=t(!0,this.options,
a);this.Date=a.Date||f.Date||Date;this.timezoneOffset=(this.useUTC=b)&&a.timezoneOffset||void 0;this.getTimezoneOffset=this.timezoneOffsetFunction();this.variableTimezone=b&&!(!a.getTimezoneOffset&&!a.timezone)}makeTime(a,b,c,d,e,m){let f,h,k;this.useUTC?(f=this.Date.UTC.apply(0,arguments),h=this.getTimezoneOffset(f),f+=h,k=this.getTimezoneOffset(f),h!==k?f+=k-h:h-36E5!==this.getTimezoneOffset(f-36E5)||n||(f-=36E5)):f=(new this.Date(a,b,u(c,1),u(d,0),u(e,0),u(m,0))).getTime();return f}timezoneOffsetFunction(){const a=
this,b=this.options,c=b.getTimezoneOffset,d=b.moment||f.moment;if(!this.useUTC)return function(a){return 6E4*(new Date(a.toString())).getTimezoneOffset()};if(b.timezone){if(d)return function(a){return 6E4*-d.tz(a,b.timezone).utcOffset()};g(25)}return this.useUTC&&c?function(a){return 6E4*c(a.valueOf())}:function(){return 6E4*(a.timezoneOffset||0)}}dateFormat(a,d,m){if(!k(d)||isNaN(d))return b.defaultOptions.lang&&b.defaultOptions.lang.invalidDate||"";a=u(a,"%Y-%m-%d %H:%M:%S");const f=this;var h=
new this.Date(d);const n=this.get("Hours",h),w=this.get("Day",h),g=this.get("Date",h),B=this.get("Month",h),G=this.get("FullYear",h),p=b.defaultOptions.lang,q=p&&p.weekdays,t=p&&p.shortWeekdays;h=l({a:t?t[w]:q[w].substr(0,3),A:q[w],d:e(g),e:e(g,2," "),w,b:p.shortMonths[B],B:p.months[B],m:e(B+1),o:B+1,y:G.toString().substr(2,2),Y:G,H:e(n),k:n,I:e(n%12||12),l:n%12||12,M:e(this.get("Minutes",h)),p:12>n?"AM":"PM",P:12>n?"am":"pm",S:e(h.getSeconds()),L:e(Math.floor(d%1E3),3)},b.dateFormats);c(h,function(b,
c){for(;-1!==a.indexOf("%"+c);)a=a.replace("%"+c,"function"===typeof b?b.call(f,d):b)});return m?a.substr(0,1).toUpperCase()+a.substr(1):a}resolveDTLFormat(b){return a(b,!0)?b:(b=z(b),{main:b[0],from:b[1],to:b[2]})}getTimeTicks(a,b,c,d){const e=this,m=[],f={};var h=new e.Date(b);const n=a.unitRange,g=a.count||1;let w;d=u(d,1);if(k(b)){e.set("Milliseconds",h,n>=p.second?0:g*Math.floor(e.get("Milliseconds",h)/g));n>=p.second&&e.set("Seconds",h,n>=p.minute?0:g*Math.floor(e.get("Seconds",h)/g));n>=p.minute&&
e.set("Minutes",h,n>=p.hour?0:g*Math.floor(e.get("Minutes",h)/g));n>=p.hour&&e.set("Hours",h,n>=p.day?0:g*Math.floor(e.get("Hours",h)/g));n>=p.day&&e.set("Date",h,n>=p.month?1:Math.max(1,g*Math.floor(e.get("Date",h)/g)));if(n>=p.month){e.set("Month",h,n>=p.year?0:g*Math.floor(e.get("Month",h)/g));var q=e.get("FullYear",h)}n>=p.year&&e.set("FullYear",h,q-q%g);n===p.week&&(q=e.get("Day",h),e.set("Date",h,e.get("Date",h)-q+d+(q<d?-7:0)));q=e.get("FullYear",h);d=e.get("Month",h);const a=e.get("Date",
h),l=e.get("Hours",h);b=h.getTime();!e.variableTimezone&&e.useUTC||!k(c)||(w=c-b>4*p.month||e.getTimezoneOffset(b)!==e.getTimezoneOffset(c));b=h.getTime();for(h=1;b<c;)m.push(b),b=n===p.year?e.makeTime(q+h*g,0):n===p.month?e.makeTime(q,d+h*g):!w||n!==p.day&&n!==p.week?w&&n===p.hour&&1<g?e.makeTime(q,d,a,l+h*g):b+n*g:e.makeTime(q,d,a+h*g*(n===p.day?1:7)),h++;m.push(b);n<=p.hour&&1E4>m.length&&m.forEach(function(a){0===a%18E5&&"000000000"===e.dateFormat("%H%M%S%L",a)&&(f[a]="day")})}m.info=l(a,{higherRanks:f,
totalRange:n*g});return m}getDateFormat(a,b,c,d){const e=this.dateFormat("%m-%d %H:%M:%S.%L",b),m={millisecond:15,second:12,minute:9,hour:6,day:3};let f,h="millisecond";for(f in p){if(a===p.week&&+this.dateFormat("%w",b)===c&&"00:00:00.000"===e.substr(6)){f="week";break}if(p[f]>a){f=h;break}if(m[f]&&e.substr(m[f])!=="01-01 00:00:00.000".substr(m[f]))break;"week"!==f&&(h=f)}return this.resolveDTLFormat(d[f]).main}}"";return m});g(b,"Core/Defaults.js",[b["Core/Chart/ChartDefaults.js"],b["Core/Color/Color.js"],
b["Core/Globals.js"],b["Core/Color/Palettes.js"],b["Core/Time.js"],b["Core/Utilities.js"]],function(b,d,f,g,y,l){const {isTouchDevice:a,svg:k}=f,{merge:c}=l,e={colors:g.colors,symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:" "},global:{},time:{Date:void 0,getTimezoneOffset:void 0,timezone:void 0,timezoneOffset:0,useUTC:!0},chart:b,title:{style:{color:"#333333",fontWeight:"bold"},text:"Chart title",align:"center",margin:15,widthAdjust:-44},subtitle:{style:{color:"#666666",fontSize:"0.8em"},text:"",align:"center",widthAdjust:-44},caption:{margin:15,style:{color:"#666666",fontSize:"0.8em"},text:"",
align:"left",verticalAlign:"bottom"},plotOptions:{},legend:{enabled:!0,align:"center",alignColumns:!0,className:"highcharts-no-tooltip",layout:"horizontal",itemMarginBottom:2,itemMarginTop:2,labelFormatter:function(){return this.name},borderColor:"#999999",borderRadius:0,navigation:{style:{fontSize:"0.8em"},activeColor:"#0022ff",inactiveColor:"#cccccc"},itemStyle:{color:"#333333",cursor:"pointer",fontSize:"0.8em",textDecoration:"none",textOverflow:"ellipsis"},itemHoverStyle:{color:"#000000"},itemHiddenStyle:{color:"#666666",
textDecoration:"line-through"},shadow:!1,itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},squareSymbol:!0,symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontSize:"0.8em",fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"#ffffff",opacity:.5,textAlign:"center"}},tooltip:{enabled:!0,animation:k,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %e %b, %H:%M:%S.%L",second:"%A, %e %b, %H:%M:%S",
minute:"%A, %e %b, %H:%M",hour:"%A, %e %b, %H:%M",day:"%A, %e %b %Y",week:"Week from %A, %e %b %Y",month:"%B %Y",year:"%Y"},footerFormat:"",headerShape:"callout",hideDelay:500,padding:8,shape:"callout",shared:!1,snap:a?25:10,headerFormat:'<span style="font-size: 0.8em">{point.key}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',backgroundColor:"#ffffff",borderWidth:void 0,shadow:!0,stickOnContact:!1,style:{color:"#333333",cursor:"default",
fontSize:"0.8em"},useHTML:!1},credits:{enabled:!0,href:"https://www.highcharts.com?credits",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#999999",fontSize:"0.6em"},text:"Highcharts.com"}};e.chart.styledMode=!1;"";const x=new y(e.time);b={defaultOptions:e,defaultTime:x,getOptions:function(){return e},setOptions:function(a){c(!0,e,a);if(a.time||a.global)f.time?f.time.update(c(e.global,e.time,a.global,a.time)):f.time=x;return e}};"";return b});g(b,"Core/Templating.js",
[b["Core/Defaults.js"],b["Core/Utilities.js"]],function(b,d){function f(a="",b,c){const d=/\{([a-zA-Z0-9:\.,;\-\/<>%_@"'= #\(\)]+)\}/g,e=/\(([a-zA-Z0-9:\.,;\-\/<>%_@"'= ]+)\)/g,m=[],h=/f$/,n=/\.([0-9])/,p=g.lang,x=c&&c.time||l,y=c&&c.numberFormatter||k,u=(a="")=>{let c;return"true"===a?!0:"false"===a?!1:(c=Number(a)).toString()===a?c:t(a,b)};let v,q,F=0,H;for(;null!==(v=d.exec(a));){const c=e.exec(v[1]);c&&(v=c,H=!0);q&&q.isBlock||(q={ctx:b,expression:v[1],find:v[0],isBlock:"#"===v[1].charAt(0),start:v.index,
startInner:v.index+v[0].length,length:v[0].length});var D=v[1].split(" ")[0].replace("#","");A[D]&&(q.isBlock&&D===q.fn&&F++,q.fn||(q.fn=D));D="else"===v[1];if(q.isBlock&&q.fn&&(v[1]===`/${q.fn}`||D))if(F)D||F--;else{var E=q.startInner;E=a.substr(E,v.index-E);void 0===q.body?(q.body=E,q.startInner=v.index+v[0].length):q.elseBody=E;q.find+=E+v[0];D||(m.push(q),q=void 0)}else q.isBlock||m.push(q);if(c&&(null===q||void 0===q||!q.isBlock))break}m.forEach(c=>{const {body:d,elseBody:e,expression:m,fn:k}=
c;var g;if(k){var l=[c],w=m.split(" ");for(g=A[k].length;g--;)l.unshift(u(w[g+1]));g=A[k].apply(b,l);c.isBlock&&"boolean"===typeof g&&(g=f(g?d:e,b))}else l=m.split(":"),g=u(l.shift()||""),l.length&&"number"===typeof g&&(l=l.join(":"),h.test(l)?(w=parseInt((l.match(n)||["","-1"])[1],10),null!==g&&(g=y(g,w,p.decimalPoint,-1<l.indexOf(",")?p.thousandsSep:""))):g=x.dateFormat(l,g));a=a.replace(c.find,z(g,""))});return H?f(a,b,c):a}function k(a,b,c,d){a=+a||0;b=+b;const f=g.lang;var m=(a.toString().split(".")[1]||
"").split("e")[0].length;const h=a.toString().split("e"),k=b;if(-1===b)b=Math.min(m,20);else if(!e(b))b=2;else if(b&&h[1]&&0>h[1]){var l=b+ +h[1];0<=l?(h[0]=(+h[0]).toExponential(l).split("e")[0],b=l):(h[0]=h[0].split(".")[0]||0,a=20>b?(h[0]*Math.pow(10,h[1])).toFixed(b):0,h[1]=0)}l=(Math.abs(h[1]?h[0]:a)+Math.pow(10,-Math.max(b,m)-1)).toFixed(b);m=String(p(l));const n=3<m.length?m.length%3:0;c=z(c,f.decimalPoint);d=z(d,f.thousandsSep);a=(0>a?"-":"")+(n?m.substr(0,n)+d:"");a=0>+h[1]&&!k?"0":a+m.substr(n).replace(/(\d{3})(?=\d)/g,
"$1"+d);b&&(a+=c+l.slice(-b));h[1]&&0!==+a&&(a+="e"+h[1]);return a}const {defaultOptions:g,defaultTime:l}=b,{extend:a,getNestedProperty:t,isArray:c,isNumber:e,isObject:u,pick:z,pInt:p}=d,A={add:(a,b)=>a+b,divide:(a,b)=>0!==b?a/b:"",eq:(a,b)=>a==b,each:function(b){const d=arguments[arguments.length-1];return c(b)?b.map((c,e)=>f(d.body,a(u(c)?c:{"@this":c},{"@index":e,"@first":0===e,"@last":e===b.length-1}))).join(""):!1},ge:(a,b)=>a>=b,gt:(a,b)=>a>b,"if":a=>!!a,le:(a,b)=>a<=b,lt:(a,b)=>a<b,multiply:(a,
b)=>a*b,ne:(a,b)=>a!=b,subtract:(a,b)=>a-b,unless:a=>!a};return{dateFormat:function(a,b,c){return l.dateFormat(a,b,c)},format:f,helpers:A,numberFormat:k}});g(b,"Dashboards/Components/KPIComponent.js",[b["Core/Renderer/HTML/AST.js"],b["Dashboards/Components/Component.js"],b["Core/Templating.js"],b["Core/Utilities.js"]],function(b,d,f,g){var k=this&&this.__awaiter||function(a,b,c,d){function e(a){return a instanceof c?a:new c(function(b){b(a)})}return new (c||(c=Promise))(function(c,f){function h(a){try{g(d.next(a))}catch(v){f(v)}}
function m(a){try{g(d["throw"](a))}catch(v){f(v)}}function g(a){a.done?c(a.value):e(a.value).then(h,m)}g((d=d.apply(a,b||[])).next())})};const {format:l}=f,{createElement:a,css:t,defined:c,getStyle:e,isArray:x,isNumber:z,merge:p,diffObjects:A}=g;class n extends d{static fromJSON(a,b){a=a.options;const c=a.chartOptions&&JSON.parse(a.chartOptions),d=JSON.parse(a.subtitle||"{}"),e=a.title&&JSON.parse(a.title);return new n(b,p(a,{chartOptions:c,title:e,subtitle:d}))}constructor(b,c){c=p(n.defaultOptions,
c);super(b,c);this.options=c;this.type="KPI";this.sync=new d.Sync(this,this.syncHandlers);this.value=a("span",{className:`${d.defaultOptions.className}-kpi-value`},{},this.contentElement);this.subtitle=a("span",{className:this.getSubtitleClassName()},{},this.contentElement);this.options.chartOptions&&(this.chartContainer=a("div",{className:`${d.defaultOptions.className}-kpi-chart-container`},{},this.contentElement))}load(){super.load();this.contentElement.style.display="flex";this.contentElement.style.flexDirection=
"column";this.parentElement.appendChild(this.element);this.updateElements();return this}resize(a,b){super.resize(a,b);!this.updatingSize&&this.dimensions.width&&this.dimensions.height&&this.updateSize(this.dimensions.width,this.dimensions.height);this.chart&&this.chart.reflow();this.updatingSize=!1;return this}updateTitleSize(a,b){this.titleElement&&(this.titleElement.style.fontSize=this.getFontSize(a,b,.08*(this.chart?1:1.7)))}getFontSize(a,b,c){return Math.max(this.options.minFontSize,Math.round(c*
Math.min(a,b)))+"px"}updateSize(a,b){this.updateTitleSize(a,b);const c=this.chart?1:1.7;this.value.style.fontSize=this.getFontSize(a,b,.15*c*(this.options.title?.7:1));this.subtitle.style.fontSize=this.getFontSize(a,b,.08*c);this.updatingSize=!0;super.resize(Number(e(this.parentElement,"width")),Number(e(this.parentElement,"height")))}render(){super.render();const a=n.charter;a&&this.options.chartOptions&&!this.chart&&this.chartContainer?this.chart=a.chart(this.chartContainer,p(n.defaultChartOptions,
this.options.chartOptions)):this.chart&&!this.options.chartOptions&&"chartOptions"in this.options&&(this.chart.destroy(),this.chart=void 0);return this}redraw(){super.redraw();this.updateElements();return this}update(a){const b=Object.create(null,{update:{get:()=>super.update}});return k(this,void 0,void 0,function*(){yield b.update.call(this,a);a.chartOptions&&this.chart&&this.chart.update(a.chartOptions);this.redraw()})}updateElements(){const {style:a,subtitle:d,valueFormat:e,valueFormatter:f}=
this.options;this.options.title&&(this.setTitle(this.options.title),this.dimensions.width&&this.dimensions.height&&this.updateTitleSize(this.dimensions.width,this.dimensions.height));let g=this.options.value;if(c(g)){let a;z(g)&&(a=g);f?g=f.call(this,g):e?g=l(e,{value:g}):z(g)&&(g=g.toLocaleString());b.setElementHTML(this.value,g);b.setElementHTML(this.subtitle,this.getSubtitle());this.prevValue=a}a&&t(this.element,a);"object"===typeof d&&(d.style&&t(this.subtitle,d.style),this.subtitle.className=
this.getSubtitleClassName());this.chartContainer&&(this.chartContainer.style.flex=this.options.chartOptions?"1":"0");this.chart&&this.chart.reflow();this.value.style.color=this.getValueColor()}getSubtitle(){const {subtitle:a,value:b}=this.options;if("string"===typeof a)return a;if(a){if(z(this.prevValue)&&z(b)){const c=b-this.prevValue;let d;if(0<c)d='<span style="color:green">&#9650;</span> +';else if(0>c)d='<span style="color:red">&#9660;</span> ';else return this.subtitle.innerHTML;if("diff"===
a.type)return d+c.toLocaleString();if("diffpercent"===a.type)return d+l("{v:,.2f}%",{v:c/this.prevValue*100})}return a.text||""}return""}getSubtitleClassName(){const {subtitle:a}=this.options;return`${d.defaultOptions.className}-kpi-subtitle`+("object"===typeof a&&a.className||"")}getValueColor(){const {threshold:a,thresholdColors:b,value:c}=this.options;if(b&&a&&z(c)){if(x(a))for(let d=a.length-1;0<=d;d--){if(c>=a[d])return d+1<b.length?b[d+1]:b[b.length-1]}else if(c>=a)return b[1];return b[0]}return""}toJSON(){const a=
super.toJSON(),b=Object.assign(Object.assign({},a),{type:"KPI",options:Object.assign(Object.assign({},a.options),{type:"KPI",value:this.options.value,subtitle:JSON.stringify(this.options.subtitle),title:JSON.stringify(this.options.title),threshold:this.options.threshold,thresholdColors:this.options.thresholdColors,chartOptions:JSON.stringify(this.options.chartOptions),valueFormat:this.options.valueFormat})});this.emit({type:"toJSON",json:a});return b}getOptions(){return Object.assign(Object.assign({},
A(this.options,n.defaultOptions)),{type:"KPI"})}}n.defaultOptions=p(d.defaultOptions,{type:"KPI",className:[d.defaultOptions.className,`${d.defaultOptions.className}-kpi`].join(" "),minFontSize:20,thresholdColors:["#f45b5b","#90ed7d"]});n.defaultChartOptions={chart:{type:"spline",backgroundColor:"transparent"},title:{text:void 0},xAxis:{visible:!1},yAxis:{visible:!1,title:{text:null}},legend:{enabled:!1},credits:{enabled:!1},tooltip:{outside:!0},plotOptions:{series:{marker:{enabled:!1}}}};return n});
g(b,"Dashboards/Plugins/HighchartsPlugin.js",[b["Dashboards/Plugins/HighchartsComponent.js"],b["Dashboards/Components/KPIComponent.js"],b["Dashboards/Plugins/HighchartsSyncHandlers.js"]],function(b,d,f){return{custom:{connectHighcharts:function(f){b.charter=f;d.charter=f}},name:"Highcharts.DashboardsPlugin",onRegister:function(g){const {Sync:k,ComponentRegistry:l}=g;l.registerComponent("Highcharts",b);l.registerComponent("KPI",d);k.defaultHandlers=Object.assign(Object.assign({},k.defaultHandlers),
f)},onUnregister:function(b){const {Sync:d}=b;Object.keys(f).forEach(b=>{d.defaultHandlers[b]===f[b]&&delete d.defaultHandlers[b]})}}});g(b,"masters/modules/dashboards-plugin.src.js",[b["Dashboards/Plugins/DataGridPlugin.js"],b["Dashboards/Globals.js"],b["Dashboards/Plugins/HighchartsPlugin.js"]],function(b,d,f){d.DataGridPlugin=b;d.HighchartsPlugin=f;d.win.Highcharts&&(f.custom.connectHighcharts(d.win.Highcharts),d.PluginHandler.addPlugin(f));d.win.DataGrid&&(b.custom.connectDataGrid(d.win.DataGrid.DataGrid),
d.PluginHandler.addPlugin(b));return d})});//# sourceMappingURL=dashboards-plugin.js.map