/*
 Highcharts Dashboards v1.0.1 (2023-07-19)

 (c) 2009-2023 Highsoft AS

 License: www.highcharts.com/license
*/
'use strict';var r=r||{};r.scope={};r.ASSUME_ES5=!1;r.ASSUME_NO_NATIVE_MAP=!1;r.ASSUME_NO_NATIVE_SET=!1;r.SIMPLE_FROUND_POLYFILL=!1;r.ISOLATE_POLYFILLS=!1;r.defineProperty=r.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,k,g){if(a==Array.prototype||a==Object.prototype)return a;a[k]=g.value;return a};
r.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<a.length;++k){var g=a[k];if(g&&g.Math==Math)return g}throw Error("Cannot find global object");};r.global=r.getGlobal(this);r.polyfills={};r.propertyToPolyfillSymbol={};r.POLYFILL_PREFIX="$jscp$";r.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
r.polyfill=function(a,k,g,c){k&&(r.ISOLATE_POLYFILLS?r.polyfillIsolated(a,k,g,c):r.polyfillUnisolated(a,k,g,c))};r.polyfillUnisolated=function(a,k){var g=r.global;a=a.split(".");for(var c=0;c<a.length-1;c++){var f=a[c];f in g||(g[f]={});g=g[f]}a=a[a.length-1];c=g[a];k=k(c);k!=c&&null!=k&&r.defineProperty(g,a,{configurable:!0,writable:!0,value:k})};
r.polyfillIsolated=function(a,k,g){var c=a.split(".");a=1===c.length;var f=c[0];f=!a&&f in r.polyfills?r.polyfills:r.global;for(var x=0;x<c.length-1;x++){var y=c[x];y in f||(f[y]={});f=f[y]}c=c[c.length-1];g=r.IS_SYMBOL_NATIVE&&"es6"===g?f[c]:null;k=k(g);null!=k&&(a?r.defineProperty(r.polyfills,c,{configurable:!0,writable:!0,value:k}):k!==g&&(r.propertyToPolyfillSymbol[c]=r.IS_SYMBOL_NATIVE?r.global.Symbol(c):r.POLYFILL_PREFIX+c,c=r.propertyToPolyfillSymbol[c],r.defineProperty(f,c,{configurable:!0,
writable:!0,value:k})))};r.polyfill("Array.prototype.includes",function(a){return a?a:function(a,g){var c=this;c instanceof String&&(c=String(c));var f=c.length;g=g||0;for(0>g&&(g=Math.max(g+f,0));g<f;g++){var x=c[g];if(x===a||Object.is(x,a))return!0}return!1}},"es7","es3");
(function(a){"object"===typeof module&&module.exports?(a["default"]=a,module.exports=a):"function"===typeof define&&define.amd?define("dashboards/modules/dashboards-plugin",["dashboards"],function(k){a(k);a.Dashboards=k;return a}):a("undefined"!==typeof Dashboards?Dashboards:void 0)})(function(a){function k(a,c,f,x){a.hasOwnProperty(c)||(a[c]=x.apply(null,f),"function"===typeof CustomEvent&&window.dispatchEvent(new CustomEvent("DashboardsModuleLoaded",{detail:{path:c,module:a[c]}})))}a=a?a._modules:
{};k(a,"Dashboards/Plugins/DataGridSyncHandlers.js",[a["Core/Utilities.js"]],function(a){const {addEvent:c}=a;return{highlight:{emitter:["highlightEmitter",function(){if("DataGrid"===this.type){const {dataGrid:f,board:a}=this;if(a){const {dataCursor:g}=a,m=[];if(f)return m.push(c(f.container,"dataGridHover",b=>{const a=this.connector&&this.connector.table;if(a){b=b.row;const e=b.querySelector(`.highcharts-datagrid-cell[data-original-data="${b.dataset.rowXIndex}"]`);g.emitCursor(a,{type:"position",
row:parseInt(b.dataset.rowIndex,10),column:e?e.dataset.columnName:void 0,state:"dataGrid.hoverRow"})}})),m.push(c(f.container,"mouseout",()=>{const b=this.connector&&this.connector.table;b&&g.emitCursor(b,{type:"position",state:"dataGrid.hoverOut"})})),function(){m.forEach(b=>b())}}}}],handler:["highlightHandler",void 0,function(){const {board:a}=this,c=b=>{b=b.cursor;if("position"===b.type){var {row:a}=b;({dataGrid:b}=this);void 0!==a&&b&&(a=b.container.querySelector(`.highcharts-datagrid-row[data-row-index="${a}"]`))&&
(b.toggleRowHighlight(a),b.hoveredRow=a)}},g=()=>{const {dataGrid:b}=this;b&&b.toggleRowHighlight(void 0)},m=()=>{const {dataCursor:b}=a;if(b){var e=this.connector&&this.connector.table;e&&(b.addListener(e.id,"point.mouseOver",c),b.addListener(e.id,"point.mouseOut",g))}},b=()=>{const b=a.dataCursor,e=this.connector&&this.connector.table;e&&(b.addListener(e.id,"point.mouseOver",c),b.addListener(e.id,"point.mouseOut",g))};a&&(m(),this.on("setConnector",()=>b()),this.on("afterSetConnector",()=>m()))}]},
extremes:{handler:function(){const {board:a}=this,c=b=>{"position"===b.cursor.type&&this.dataGrid&&b.cursors.length&&(b=b.cursors[b.cursors.length-1],"row"in b&&"number"===typeof b.row&&({row:b}=b,this.dataGrid.scrollToRow(b)))},g=()=>{const {dataCursor:b}=a;if(b){var f=this.connector&&this.connector.table;f&&b.addListener(f.id,"xAxis.extremes.min",c)}},m=()=>{const b=this.connector&&this.connector.table,{dataCursor:f}=a;b&&f.removeListener(b.id,"xAxis.extremes.min",c)};a&&(g(),this.on("setConnector",
()=>m()),this.on("afterSetConnector",()=>g()))}}}});k(a,"Dashboards/Plugins/DataGridComponent.js",[a["Dashboards/Components/Component.js"],a["Data/Converters/DataConverter.js"],a["Dashboards/Plugins/DataGridSyncHandlers.js"],a["Core/Utilities.js"]],function(a,c,f,x){var g=this&&this.__awaiter||function(d,b,a,e){function f(d){return d instanceof a?d:new a(function(h){h(d)})}return new (a||(a=Promise))(function(a,h){function l(l){try{u(e.next(l))}catch(A){h(A)}}function w(l){try{u(e["throw"](l))}catch(A){h(A)}}
function u(h){h.done?a(h.value):f(h.value).then(l,w)}u((e=e.apply(d,b||[])).next())})};const {diffObjects:m,merge:b,uniqueKey:v}=x;class e extends a{static onUpdate(d,b){if(d=d.target){var a=d.closest(".highcharts-datagrid-row"),e=d.closest(".highcharts-datagrid-cell");const f=new c;a&&a instanceof HTMLElement&&e&&e instanceof HTMLElement&&(a=a.dataset.rowIndex,{columnName:e}=e.dataset,void 0!==a&&void 0!==e&&(b=b.table.modified))&&(d=f.asGuessedType(d.value),d instanceof Date&&(d=d.toString()),b.setCell(e,
parseInt(a,10),d))}}static fromJSON(d,a){const f=d.options,u=JSON.parse(d.options.dataGridOptions||"");a=new e(a,b(f,{dataGridOptions:u,syncHandlers:e.syncHandlers}));a.emit({type:"fromJSON",json:d});return a}constructor(d,u){u=b(e.defaultOptions,u);super(d,u);this.connectorListeners=[];this.options=u;this.type="DataGrid";this.options.dataGridClassName&&this.contentElement.classList.add(this.options.dataGridClassName);this.options.dataGridID&&(this.contentElement.id=this.options.dataGridID);this.syncHandlers=
this.handleSyncOptions(f);this.sync=new e.Sync(this,this.syncHandlers);this.dataGridOptions=this.options.dataGridOptions||{};this.innerResizeTimeouts=[];this.on("tableChanged",()=>{var d;null===(d=this.dataGrid)||void 0===d?void 0:d.update({dataTable:this.filterColumns()})});a.addInstance(this)}load(){this.emit({type:"load"});super.load();this.parentElement.appendChild(this.element);this.hasLoaded=!0;if(this.connector&&!this.connectorListeners.length){const d=this.connectorListeners;d.push(this.connector.on("afterLoad",
d=>{d.table&&this.connector&&this.connector.table.setColumns(d.table.getColumns())}));d.push(this.connector.table.on("afterSetCell",d=>{const a=this.dataGrid;let b=!0;a&&Array.prototype.slice.call(a.rowElements[d.rowIndex].childNodes).forEach(a=>{if(0<a.childElementCount){var e=a.childNodes[0];e="string"===typeof d.cellValue?e.value:+e.value;a.dataset.columnName===d.columnName&&e===d.cellValue&&(b=!1)}});b?this.update({}):void 0}))}this.emit({type:"afterLoad"});return this}render(){this.emit({type:"beforeRender"});
super.render();this.dataGrid||(this.dataGrid=this.constructDataGrid());this.connector&&this.dataGrid&&this.dataGrid.dataTable.modified!==this.connector.table.modified&&this.dataGrid.update({dataTable:this.filterColumns()});this.sync.start();this.emit({type:"afterRender"});this.setupConnectorUpdate();return this}redraw(){super.redraw();return this.render()}resize(d,a){this.dataGrid&&(super.resize(d,a),this.dataGrid.setSize(d,a))}update(d){const a=Object.create(null,{update:{get:()=>super.update}});
var b;return g(this,void 0,void 0,function*(){if((null===(b=d.connector)||void 0===b?void 0:b.id)!==this.connectorId){const d=this.connectorListeners;for(let a=0,b=d.length;a<b;++a)d[a]();d.length=0}yield a.update.call(this,d);this.dataGrid&&this.dataGrid.update(this.options.dataGridOptions||{});this.emit({type:"afterUpdate"})})}constructDataGrid(){if(e.DataGridConstructor)return this.dataGrid=new e.DataGridConstructor(this.contentElement,Object.assign(Object.assign({},this.options.dataGridOptions),
{dataTable:this.connector&&this.connector.table.modified}));throw Error("DataGrid not connected.");}setupConnectorUpdate(){const {connector:d,dataGrid:a}=this;if(d&&a)a.on("cellClick",a=>{"input"in a&&a.input.addEventListener("keyup",a=>this.options.onUpdate(a,d))})}filterColumns(){var a,b=null===(a=this.connector)||void 0===a?void 0:a.table.modified;const e=this.options.visibleColumns;if(b){if(null===e||void 0===e||!e.length)return b;a=b.getColumnNames().filter(a=>0<(null===e||void 0===e?void 0:
e.length)&&!e.includes(a));b=b.clone();b.deleteColumns(a);return b}}toJSON(){var a=JSON.stringify(this.options.dataGridOptions);const b=super.toJSON();a=Object.assign(Object.assign({},b),{options:Object.assign(Object.assign({},b.options),{dataGridOptions:a})});this.emit({type:"toJSON",json:a});return a}getOptions(){return Object.assign(Object.assign({},m(this.options,e.defaultOptions)),{type:"DataGrid"})}}e.syncHandlers=f;e.defaultOptions=b(a.defaultOptions,{dataGridClassName:"dataGrid-container",
dataGridID:"dataGrid-"+v(),dataGridOptions:{},editableOptions:[{name:"connectorName",propertyPath:["connector","id"],type:"select"}],syncHandlers:f,onUpdate:e.onUpdate});return e});k(a,"Dashboards/Plugins/DataGridPlugin.js",[a["Dashboards/Plugins/DataGridComponent.js"]],function(a){return{custom:{connectDataGrid:function(c){a.DataGridConstructor=c}},name:"DataGrid.DashboardsPlugin",onRegister:function(c){({ComponentRegistry:c}=c);c.registerComponent("DataGrid",a)},onUnregister:function(){}}});k(a,
"Dashboards/Plugins/HighchartsSyncHandlers.js",[a["Core/Utilities.js"]],function(a){const {addEvent:c}=a;return{extremes:{emitter:function(){if("Highcharts"===this.type){const a=this,g=[];this.on("afterRender",()=>{const {chart:f,connector:m,board:b}=a,v=m&&m.table,{dataCursor:e}=b;if(v&&f){const a=a=>{var b=!!a.resetSelection;if((!a.trigger||a.trigger&&"dashboards-sync"!==a.trigger)&&!b){var h=a.target;const l=h.series.filter(a=>v.hasColumns([a.name])),[d]=l.length?l:h.series;if(d){b=d.points.filter(a=>
a.isInside||!1);const w={type:"position",state:`${h.coll}.extremes.min`},f={type:"position",state:`${h.coll}.extremes.max`};l.length&&"xAxis"===h.coll&&b.length&&(h=h.dateTime&&v.hasColumns(["x"])?"x":d.name,w.row=b[0].index,w.column=h,f.row=b[b.length-1].index,f.column=h);e.emitCursor(v,w,a,!0).emitCursor(v,f,a,!0)}}},b=()=>f.axes.map(b=>c(b,"afterSetExtremes",a));let m=b();const p=()=>{m.forEach(a=>{a()});m=[]};g.push(c(f,"selection",a=>{a.resetSelection&&(p(),e.emitCursor(v,{type:"position",state:"chart.zoomOut"},
a),m.push(...b()))}));g.push(()=>{e.remitCursor(v.id,{type:"position",state:"xAxis.extremes.min"});e.remitCursor(v.id,{type:"position",state:"xAxis.extremes.max"});p()})}});return function(){g.forEach(a=>a())}}},handler:function(){const {chart:a,board:c}=this;a&&c&&["xAxis","yAxis"].forEach(f=>{const g=[],b=b=>{const {cursor:d,event:e}=b;if("position"===d.type){const b=e&&e.target;if(b&&a){let d=!1;a[f].forEach(a=>{b.coll===a.coll&&b!==a&&null!==b.min&&null!==b.max&&a.max!==b.max&&a.min!==b.min&&
(a.setExtremes(b.min,b.max,!1,void 0,{trigger:"dashboards-sync"}),d=!0)});d&&!a.resetZoomButton&&a.showResetZoom();a.redraw()}}},v=()=>{const {dataCursor:d}=c,{connector:e}=this;if(e){const {table:c}=e;d.addListener(c.id,`${f}.extremes.min`,b);d.addListener(c.id,`${f}.extremes.max`,b);const m=()=>{a.zoomOut();setTimeout(()=>{this.element.querySelectorAll(".highcharts-reset-zoom").forEach(a=>{a.remove()})})};d.addListener(c.id,"chart.zoomOut",m);g.push(()=>{d.removeListener(c.id,`${f}.extremes.min`,
b);d.removeListener(c.id,`${f}.extremes.max`,b);d.removeListener(c.id,"chart.zoomOut",m)})}},e=()=>{g.forEach(a=>a())};c&&(v(),this.on("setConnector",()=>e()),this.on("afterSetConnector",()=>v()))})}},highlight:{emitter:["highlightEmitter",function(){if("Highcharts"===this.type){const {chart:a,board:c}=this;if(c){const {dataCursor:f}=c;this.on("afterRender",()=>{const c=this.connector&&this.connector.table;a&&a.series&&c&&a.series.forEach(a=>{a.update({point:{events:{mouseOver:function(){let b=0;
const e=c.getModifier();e&&"getModifiedTableOffset"in e&&(b=e.getModifiedTableOffset(c));f.emitCursor(c,{type:"position",row:b+this.index,column:a.name,state:"point.mouseOver"})},mouseOut:function(){let b=0;const e=c.getModifier();e&&"getModifiedTableOffset"in e&&(b=e.getModifiedTableOffset(c));f.emitCursor(c,{type:"position",row:b+this.index,column:a.name,state:"point.mouseOut"})}}}})})});return function(){a&&a.series&&a.series.forEach(a=>{a.update({point:{events:{mouseOver:void 0,mouseOut:void 0}}})})}}}}],
handler:function(){const {chart:a,board:c}=this,g=b=>{const d=this.connector&&this.connector.table;if(d){var e=0,c=d.getModifier();c&&"getModifiedTableOffset"in c&&(e=c.getModifiedTableOffset(d));if(a&&a.series.length){const d=b.cursor;"position"===d.type&&([b]=1<a.series.length&&d.column?a.series.filter(a=>a.name===d.column):a.series,b&&b.visible&&void 0!==d.row&&(e=b.points[d.row-e])&&a.tooltip&&a.tooltip.refresh(e))}}},m=()=>{a&&a.series.length&&a.tooltip&&a.tooltip.hide()},b=()=>{const {dataCursor:a}=
c;if(a){const b=this.connector&&this.connector.table;b&&(a.addListener(b.id,"point.mouseOver",g),a.addListener(b.id,"dataGrid.hoverRow",g),a.addListener(b.id,"point.mouseOut",m),a.addListener(b.id,"dataGrid.hoverOut",m))}},v=()=>{const a=this.connector&&this.connector.table;a&&(c.dataCursor.removeListener(a.id,"point.mouseOver",g),c.dataCursor.removeListener(a.id,"dataGrid.hoverRow",g),c.dataCursor.removeListener(a.id,"point.mouseOut",m),c.dataCursor.removeListener(a.id,"dataGrid.hoverOut",m))};c&&
(b(),this.on("setConnector",()=>v()),this.on("afterSetConnector",()=>b()))}},visibility:{emitter:function(){if("Highcharts"===this.type){const a=this;return this.on("afterRender",()=>{const {chart:c,connector:f,board:g}=a,b=f&&f.table;if(b&&g&&c){const {dataCursor:a}=g,{series:e}=c;e.forEach(d=>{d.update({events:{show:function(){a.emitCursor(b,{type:"position",state:"series.show",column:this.name})},hide:function(){a.emitCursor(b,{type:"position",state:"series.hide",column:this.name})}}})})}})}},
handler:function(){const a=this,{board:c}=this,g=(a,b)=>{for(const d of a)if(d.name===b)return d},m=b=>{const d=a.chart;d&&"position"===b.cursor.type&&void 0!==b.cursor.column&&(b=g(d.series,b.cursor.column))&&b.setVisible(!0,!0)},b=b=>{const d=a.chart;d&&"position"===b.cursor.type&&void 0!==b.cursor.column&&(b=g(d.series,b.cursor.column))&&b.setVisible(!1,!0)},v=()=>{const {dataCursor:a}=c;if(a){var e=this.connector&&this.connector.table;e&&(a.addListener(e.id,"series.show",m),a.addListener(e.id,
"series.hide",b))}},e=()=>{const a=this.connector&&this.connector.table;a&&(c.dataCursor.removeListener(a.id,"series.show",m),c.dataCursor.removeListener(a.id,"series.hide",b))};c&&(v(),this.on("setConnector",()=>e()),this.on("afterSetConnector",()=>v()))}}}});k(a,"Dashboards/Plugins/HighchartsComponent.js",[a["Dashboards/Components/Component.js"],a["Data/Converters/DataConverter.js"],a["Data/DataTable.js"],a["Dashboards/Globals.js"],a["Dashboards/Plugins/HighchartsSyncHandlers.js"],a["Core/Utilities.js"]],
function(a,c,f,k,y,m){var b=this&&this.__awaiter||function(a,b,d,c){function h(a){return a instanceof d?a:new d(function(b){b(a)})}return new (d||(d=Promise))(function(l,d){function w(a){try{f(c.next(a))}catch(t){d(t)}}function e(a){try{f(c["throw"](a))}catch(t){d(t)}}function f(a){a.done?l(a.value):h(a.value).then(w,e)}f((c=c.apply(a,b||[])).next())})};const {addEvent:g,createElement:e,merge:d,splat:u,uniqueKey:x,error:p,diffObjects:z}=m;class n extends a{static fromJSON(a,b){const h=a.options,l=
JSON.parse(a.options.chartOptions||"{}");b=new n(b,d(h,{chartOptions:l,syncHandlers:n.syncHandlers}));b.emit({type:"fromJSON",json:a});return b}constructor(b,l){l=d(n.defaultOptions,l);super(b,l);this.options=l;this.chartConstructor=this.options.chartConstructor;this.type="Highcharts";this.chartContainer=e("figure",void 0,void 0,void 0,!0);this.setOptions();this.sync=new n.Sync(this,this.syncHandlers);this.chartOptions=d(this.options.chartOptions||{chart:{}},{tooltip:{}});this.on("tableChanged",()=>
this.updateSeries());if(this.connector)this.connector.on("afterLoad",a=>{a.table&&this.connector&&this.connector.table.setColumns(a.table.getColumns())});this.innerResizeTimeouts=[];a.addInstance(this)}load(){this.emit({type:"load"});super.load();this.parentElement.appendChild(this.element);this.contentElement.appendChild(this.chartContainer);this.hasLoaded=!0;this.emit({type:"afterLoad"});return this}render(){this.emit({type:"beforeRender"});super.render();this.chart=this.getChart();this.updateSeries();
this.sync.start();this.emit({type:"afterRender"});this.setupConnectorUpdate();return this}resize(a,b){for(super.resize(a,b);this.innerResizeTimeouts.length;)(a=this.innerResizeTimeouts.pop())&&clearTimeout(a);this.innerResizeTimeouts.push(setTimeout(()=>{this.chart&&this.chart.setSize(null,this.contentElement.clientHeight,!1)},33));return this}setupConnectorUpdate(){const {connector:a,chart:b}=this;a&&b&&this.options.allowConnectorUpdate&&b.series.forEach(b=>{b.points.forEach(b=>{g(b,"drag",()=>{this.onChartUpdate(b,
a)})})})}setOptions(){this.options.chartClassName&&this.chartContainer.classList.add(this.options.chartClassName);this.options.chartID&&(this.chartContainer.id=this.options.chartID);this.syncHandlers=this.handleSyncOptions(y)}onChartUpdate(a,b){b=b.table;const h=a.series.name,l=a.x;a=(new c).asNumber(a.y);b.setCell(h,l,a)}update(a,l=!0){const h=Object.create(null,{update:{get:()=>super.update}});return b(this,void 0,void 0,function*(){yield h.update.call(this,a,!1);this.setOptions();this.chart&&this.chart.update(d(this.options.chartOptions)||
{});this.emit({type:"afterUpdate"});l&&this.redraw()})}updateSeries(){if(this.chart&&this.connector){this.presentationTable=this.presentationModifier?this.connector.table.modified.clone():this.connector.table;const {id:a}=this.connector.table,{chart:b}=this,d=this.options.columnAssignment||{},c={};this.presentationModifier&&(this.presentationTable=this.presentationModifier.modifyTable(this.presentationTable).modified);const e=this.presentationTable;this.emit({type:"afterPresentationModifier",table:e});
const A=e.modified.getColumnNames().filter(a=>this.activeGroup&&!1===this.activeGroup.getSharedState().getColumnVisibility(a)&&!d[a]||null===d[a]?!1:"x"===d[a]?(c[a]=a,!1):!0);A.map((h,d)=>{let l=0;for(;l<b.series.length;){const h=b.series[l],c=h.options.id===`${a}-series-${d}`,e=-1!==A.indexOf(h.name);l++;if(e&&c)return h;!e&&c&&h.destroy()}return b.addSeries({name:h,id:`${a}-series-${d}`},!1)}).forEach(a=>{var b=Object.keys(c)[0];const h=new f({columns:e.modified.getColumns([b,a.name])});h.renameColumn(a.name,
"y");b&&h.renameColumn(b,"x");b=h.getRowObjects().reduce((a,b)=>{a.push([b.x,b.y]);return a},[]);a.setData(b)})}}getChart(){return this.chart||this.createChart()}createChart(){const a=n.charter||k.win.Highcharts;if("chart"!==this.chartConstructor){const b=a[this.chartConstructor];if(b)try{return b(this.chartContainer,this.chartOptions)}catch(w){p("The Highcharts component is misconfigured: `"+this.cell.id+"`")}}if("function"!==typeof a.chart)throw Error("Chart constructor not found");return this.chart=
a.chart(this.chartContainer,this.chartOptions)}registerChartEvents(){if(this.chart&&this.chart.options){const a=this.chart.options;"chart series yAxis xAxis colorAxis annotations navigation".split(" ").map(b=>{let h=a[b]||{};!Array.isArray(h)&&h.events&&(h=[h]);return h&&"object"===typeof h&&Array.isArray(h)?h.reduce((a,h,d)=>{h&&h.events&&(a[h.id||`${b}-${d}`]=h.events);return a},{})||{}:{}}).forEach(a=>{Object.keys(a).forEach(b=>{const h=a[b];Object.keys(h).forEach(a=>{this.callbackRegistry.addCallback(`${b}-${a}`,
{type:"seriesEvent",func:h[a]})})})})}}setConnector(a){var b;const h=this.chart;if(this.connector&&h&&h.series&&this.connector.table.id!==(null===a||void 0===a?void 0:a.table.id)){const a=this.connector.table.id;for(let d=h.series.length-1;0<=d;d--){const c=h.series[d];-1!==(null===(b=c.options.id)||void 0===b?void 0:b.indexOf(a))&&c.remove(!1)}}super.setConnector(a);return this}toJSON(){var a=JSON.stringify(this.options.chartOptions);const b=this.options.chartConstructor;this.registerChartEvents();
const d=super.toJSON();a=Object.assign(Object.assign({},d),{type:"Highcharts",options:Object.assign(Object.assign({},d.options),{chartOptions:a,chartConstructor:b,type:"Highcharts",sync:{}})});this.emit({type:"toJSON",json:a});return a}getOptions(){return Object.assign(Object.assign({},z(this.options,n.defaultOptions)),{type:"Highcharts"})}getEditableOptions(){var a;const b=this.options,c=this.chart,e=c&&c.options,f=e&&(null===(a=e.chart)||void 0===a?void 0:a.type)||"line";return d(b,{chartOptions:e},
{chartOptions:{yAxis:u(c&&c.yAxis[0].options),xAxis:u(c&&c.xAxis[0].options),plotOptions:{series:(e&&e.plotOptions||{})[f]}}})}getEditableOptionValue(a){if(a)return 1===a.length&&"chartOptions"===a[0]?JSON.stringify(this.options.chartOptions,null,2):super.getEditableOptionValue.call(this,a)}}n.syncHandlers=y;n.defaultOptions=d(a.defaultOptions,{allowConnectorUpdate:!0,chartClassName:"chart-container",chartID:"chart-"+x(),chartOptions:{chart:{styledMode:!0},series:[]},chartConstructor:"",editableOptions:(a.defaultOptions.editableOptions||
[]).concat([{name:"chartOptions",type:"nested",nestedOptions:[{name:"chart",options:[{name:"title",propertyPath:["chartOptions","title","text"],type:"input"},{name:"subtitle",propertyPath:["chartOptions","subtitle","text"],type:"input"},{name:"type",propertyPath:["chartOptions","chart","type"],type:"select",selectOptions:[{name:"column",iconURL:"series-types/icon-column.svg"},{name:"line",iconURL:"series-types/icon-line.svg"},{name:"scatter",iconURL:"series-types/icon-scatter.svg"},{name:"pie",iconURL:"series-types/icon-pie.svg"}]}]},
{name:"xAxis",options:[{name:"title",propertyPath:["chartOptions","xAxis","title","text"],type:"input"},{name:"type",propertyPath:["chartOptions","xAxis","type"],type:"select",selectOptions:[{name:"linear"},{name:"datetime"},{name:"logarithmic"}]}]},{name:"yAxis",options:[{name:"title",propertyPath:["chartOptions","yAxis","title","text"],type:"input"},{name:"type",propertyPath:["chartOptions","yAxis","type"],type:"select",selectOptions:[{name:"linear"},{name:"datetime"},{name:"logarithmic"}]}]},{name:"legend",
showToggle:!0,propertyPath:["chartOptions","legend","enabled"],options:[{name:"align",propertyPath:["chartOptions","legend","align"],type:"select",selectOptions:[{name:"left"},{name:"center"},{name:"right"}]}]},{name:"tooltip",showToggle:!0,propertyPath:["chartOptions","tooltip","enabled"],options:[{name:"split",propertyPath:["chartOptions","tooltip","split"],type:"toggle"}]},{name:"dataLabels",propertyPath:["chartOptions","plotOptions","series","dataLabels","enabled"],showToggle:!0,options:[{name:"align",
propertyPath:["chartOptions","plotOptions","series","dataLabels","align"],type:"select",selectOptions:[{name:"left"},{name:"center"},{name:"right"}]}]},{name:"credits",showToggle:!0,propertyPath:["chartOptions","credits","enabled"],options:[{name:"name",propertyPath:["chartOptions","credits","text"],type:"input"},{name:"url",propertyPath:["chartOptions","credits","href"],type:"input"}]}]},{name:"chartConfig",propertyPath:["chartOptions"],type:"textarea"},{name:"chartClassName",propertyPath:["chartClassName"],
type:"input"},{name:"chartID",propertyPath:["chartID"],type:"input"}]),syncHandlers:y,editableOptionsBindings:d(a.defaultOptions.editableOptionsBindings,{skipRedraw:["chartOptions","chartConfig"]}),columnAssignment:{}});return n});k(a,"Core/Chart/ChartDefaults.js",[],function(){return{alignThresholds:!1,panning:{enabled:!1,type:"x"},styledMode:!1,borderRadius:0,colorCount:10,allowMutatingData:!0,ignoreHiddenSeries:!0,spacing:[10,10,15,10],resetZoomButton:{theme:{zIndex:6},position:{align:"right",
x:-10,y:10}},reflow:!0,type:"line",zooming:{singleTouch:!1,resetButton:{theme:{zIndex:6},position:{align:"right",x:-10,y:10}}},width:null,height:null,borderColor:"#334eff",backgroundColor:"#ffffff",plotBorderColor:"#cccccc"}});k(a,"Core/Color/Color.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,c){const {isNumber:f,merge:g,pInt:k}=c;class m{static parse(a){return a?new m(a):m.None}constructor(b){this.rgba=[NaN,NaN,NaN,NaN];this.input=b;const c=a.Color;if(c&&c!==m)return new c(b);this.init(b)}init(a){let b;
let c;if("object"===typeof a&&"undefined"!==typeof a.stops)this.stops=a.stops.map(a=>new m(a[1]));else if("string"===typeof a){this.input=a=m.names[a.toLowerCase()]||a;if("#"===a.charAt(0)){var d=a.length;var f=parseInt(a.substr(1),16);7===d?b=[(f&16711680)>>16,(f&65280)>>8,f&255,1]:4===d&&(b=[(f&3840)>>4|(f&3840)>>8,(f&240)>>4|f&240,(f&15)<<4|f&15,1])}if(!b)for(f=m.parsers.length;f--&&!b;)c=m.parsers[f],(d=c.regex.exec(a))&&(b=c.parse(d))}b&&(this.rgba=b)}get(a){const b=this.input,c=this.rgba;if("object"===
typeof b&&"undefined"!==typeof this.stops){const c=g(b);c.stops=[].slice.call(c.stops);this.stops.forEach((b,d)=>{c.stops[d]=[c.stops[d][0],b.get(a)]});return c}return c&&f(c[0])?"rgb"===a||!a&&1===c[3]?"rgb("+c[0]+","+c[1]+","+c[2]+")":"a"===a?`${c[3]}`:"rgba("+c.join(",")+")":b}brighten(a){const b=this.rgba;if(this.stops)this.stops.forEach(function(b){b.brighten(a)});else if(f(a)&&0!==a)for(let c=0;3>c;c++)b[c]+=k(255*a),0>b[c]&&(b[c]=0),255<b[c]&&(b[c]=255);return this}setOpacity(a){this.rgba[3]=
a;return this}tweenTo(a,c){const b=this.rgba,d=a.rgba;if(!f(b[0])||!f(d[0]))return a.input||"none";a=1!==d[3]||1!==b[3];return(a?"rgba(":"rgb(")+Math.round(d[0]+(b[0]-d[0])*(1-c))+","+Math.round(d[1]+(b[1]-d[1])*(1-c))+","+Math.round(d[2]+(b[2]-d[2])*(1-c))+(a?","+(d[3]+(b[3]-d[3])*(1-c)):"")+")"}}m.names={white:"#ffffff",black:"#000000"};m.parsers=[{regex:/rgba\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]?(?:\.[0-9]+)?)\s*\)/,parse:function(a){return[k(a[1]),k(a[2]),k(a[3]),
parseFloat(a[4],10)]}},{regex:/rgb\(\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*,\s*([0-9]{1,3})\s*\)/,parse:function(a){return[k(a[1]),k(a[2]),k(a[3]),1]}}];m.None=new m("");"";return m});k(a,"Core/Color/Palettes.js",[],function(){return{colors:"#2caffe #544fc5 #00e272 #fe6a35 #6b8abc #d568fb #2ee0ca #fa4b42 #feb56a #91e8e1".split(" ")}});k(a,"Core/Time.js",[a["Core/Globals.js"],a["Core/Utilities.js"]],function(a,c){const {win:f}=a,{defined:g,error:k,extend:m,isObject:b,merge:v,objectEach:e,pad:d,pick:u,
splat:D,timeUnits:p}=c,z=a.isSafari&&f.Intl&&f.Intl.DateTimeFormat.prototype.formatRange,n=a.isSafari&&f.Intl&&!f.Intl.DateTimeFormat.prototype.formatRange;class h{constructor(a){this.options={};this.variableTimezone=this.useUTC=!1;this.Date=f.Date;this.getTimezoneOffset=this.timezoneOffsetFunction();this.update(a)}get(a,b){if(this.variableTimezone||this.timezoneOffset){const c=b.getTime(),h=c-this.getTimezoneOffset(b);b.setTime(h);a=b["getUTC"+a]();b.setTime(c);return a}return this.useUTC?b["getUTC"+
a]():b["get"+a]()}set(a,b,c){if(this.variableTimezone||this.timezoneOffset){if("Milliseconds"===a||"Seconds"===a||"Minutes"===a&&0===this.getTimezoneOffset(b)%36E5)return b["setUTC"+a](c);var h=this.getTimezoneOffset(b);h=b.getTime()-h;b.setTime(h);b["setUTC"+a](c);a=this.getTimezoneOffset(b);h=b.getTime()+a;return b.setTime(h)}return this.useUTC||z&&"FullYear"===a?b["setUTC"+a](c):b["set"+a](c)}update(a={}){const b=u(a.useUTC,!0);this.options=a=v(!0,this.options,a);this.Date=a.Date||f.Date||Date;
this.timezoneOffset=(this.useUTC=b)&&a.timezoneOffset||void 0;this.getTimezoneOffset=this.timezoneOffsetFunction();this.variableTimezone=b&&!(!a.getTimezoneOffset&&!a.timezone)}makeTime(a,b,c,h,d,f){let e,l,A;this.useUTC?(e=this.Date.UTC.apply(0,arguments),l=this.getTimezoneOffset(e),e+=l,A=this.getTimezoneOffset(e),l!==A?e+=A-l:l-36E5!==this.getTimezoneOffset(e-36E5)||n||(e-=36E5)):e=(new this.Date(a,b,u(c,1),u(h,0),u(d,0),u(f,0))).getTime();return e}timezoneOffsetFunction(){const a=this,b=this.options,
c=b.getTimezoneOffset,h=b.moment||f.moment;if(!this.useUTC)return function(a){return 6E4*(new Date(a.toString())).getTimezoneOffset()};if(b.timezone){if(h)return function(a){return 6E4*-h.tz(a,b.timezone).utcOffset()};k(25)}return this.useUTC&&c?function(a){return 6E4*c(a.valueOf())}:function(){return 6E4*(a.timezoneOffset||0)}}dateFormat(b,c,h){if(!g(c)||isNaN(c))return a.defaultOptions.lang&&a.defaultOptions.lang.invalidDate||"";b=u(b,"%Y-%m-%d %H:%M:%S");const f=this;var l=new this.Date(c);const n=
this.get("Hours",l),w=this.get("Day",l),k=this.get("Date",l),p=this.get("Month",l),G=this.get("FullYear",l),t=a.defaultOptions.lang,q=t&&t.weekdays,F=t&&t.shortWeekdays;l=m({a:F?F[w]:q[w].substr(0,3),A:q[w],d:d(k),e:d(k,2," "),w,b:t.shortMonths[p],B:t.months[p],m:d(p+1),o:p+1,y:G.toString().substr(2,2),Y:G,H:d(n),k:n,I:d(n%12||12),l:n%12||12,M:d(this.get("Minutes",l)),p:12>n?"AM":"PM",P:12>n?"am":"pm",S:d(l.getSeconds()),L:d(Math.floor(c%1E3),3)},a.dateFormats);e(l,function(a,h){for(;-1!==b.indexOf("%"+
h);)b=b.replace("%"+h,"function"===typeof a?a.call(f,c):a)});return h?b.substr(0,1).toUpperCase()+b.substr(1):b}resolveDTLFormat(a){return b(a,!0)?a:(a=D(a),{main:a[0],from:a[1],to:a[2]})}getTimeTicks(a,b,c,h){const d=this,e=[],f={};var l=new d.Date(b);const n=a.unitRange,k=a.count||1;let w;h=u(h,1);if(g(b)){d.set("Milliseconds",l,n>=p.second?0:k*Math.floor(d.get("Milliseconds",l)/k));n>=p.second&&d.set("Seconds",l,n>=p.minute?0:k*Math.floor(d.get("Seconds",l)/k));n>=p.minute&&d.set("Minutes",l,n>=
p.hour?0:k*Math.floor(d.get("Minutes",l)/k));n>=p.hour&&d.set("Hours",l,n>=p.day?0:k*Math.floor(d.get("Hours",l)/k));n>=p.day&&d.set("Date",l,n>=p.month?1:Math.max(1,k*Math.floor(d.get("Date",l)/k)));if(n>=p.month){d.set("Month",l,n>=p.year?0:k*Math.floor(d.get("Month",l)/k));var q=d.get("FullYear",l)}n>=p.year&&d.set("FullYear",l,q-q%k);n===p.week&&(q=d.get("Day",l),d.set("Date",l,d.get("Date",l)-q+h+(q<h?-7:0)));q=d.get("FullYear",l);h=d.get("Month",l);const a=d.get("Date",l),m=d.get("Hours",l);
b=l.getTime();!d.variableTimezone&&d.useUTC||!g(c)||(w=c-b>4*p.month||d.getTimezoneOffset(b)!==d.getTimezoneOffset(c));b=l.getTime();for(l=1;b<c;)e.push(b),b=n===p.year?d.makeTime(q+l*k,0):n===p.month?d.makeTime(q,h+l*k):!w||n!==p.day&&n!==p.week?w&&n===p.hour&&1<k?d.makeTime(q,h,a,m+l*k):b+n*k:d.makeTime(q,h,a+l*k*(n===p.day?1:7)),l++;e.push(b);n<=p.hour&&1E4>e.length&&e.forEach(function(a){0===a%18E5&&"000000000"===d.dateFormat("%H%M%S%L",a)&&(f[a]="day")})}e.info=m(a,{higherRanks:f,totalRange:n*
k});return e}getDateFormat(a,b,c,d){const h=this.dateFormat("%m-%d %H:%M:%S.%L",b),l={millisecond:15,second:12,minute:9,hour:6,day:3};let e,f="millisecond";for(e in p){if(a===p.week&&+this.dateFormat("%w",b)===c&&"00:00:00.000"===h.substr(6)){e="week";break}if(p[e]>a){e=f;break}if(l[e]&&h.substr(l[e])!=="01-01 00:00:00.000".substr(l[e]))break;"week"!==e&&(f=e)}return this.resolveDTLFormat(d[e]).main}}"";return h});k(a,"Core/Defaults.js",[a["Core/Chart/ChartDefaults.js"],a["Core/Color/Color.js"],a["Core/Globals.js"],
a["Core/Color/Palettes.js"],a["Core/Time.js"],a["Core/Utilities.js"]],function(a,c,f,k,y,m){const {isTouchDevice:b,svg:g}=f,{merge:e}=m,d={colors:k.colors,symbols:["circle","diamond","square","triangle","triangle-down"],lang:{loading:"Loading...",months:"January February March April May June July August September October November December".split(" "),shortMonths:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),weekdays:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
decimalPoint:".",numericSymbols:"kMGTPE".split(""),resetZoom:"Reset zoom",resetZoomTitle:"Reset zoom level 1:1",thousandsSep:" "},global:{},time:{Date:void 0,getTimezoneOffset:void 0,timezone:void 0,timezoneOffset:0,useUTC:!0},chart:a,title:{style:{color:"#333333",fontWeight:"bold"},text:"Chart title",align:"center",margin:15,widthAdjust:-44},subtitle:{style:{color:"#666666",fontSize:"0.8em"},text:"",align:"center",widthAdjust:-44},caption:{margin:15,style:{color:"#666666",fontSize:"0.8em"},text:"",
align:"left",verticalAlign:"bottom"},plotOptions:{},legend:{enabled:!0,align:"center",alignColumns:!0,className:"highcharts-no-tooltip",layout:"horizontal",itemMarginBottom:2,itemMarginTop:2,labelFormatter:function(){return this.name},borderColor:"#999999",borderRadius:0,navigation:{style:{fontSize:"0.8em"},activeColor:"#0022ff",inactiveColor:"#cccccc"},itemStyle:{color:"#333333",cursor:"pointer",fontSize:"0.8em",textDecoration:"none",textOverflow:"ellipsis"},itemHoverStyle:{color:"#000000"},itemHiddenStyle:{color:"#666666",
textDecoration:"line-through"},shadow:!1,itemCheckboxStyle:{position:"absolute",width:"13px",height:"13px"},squareSymbol:!0,symbolPadding:5,verticalAlign:"bottom",x:0,y:0,title:{style:{fontSize:"0.8em",fontWeight:"bold"}}},loading:{labelStyle:{fontWeight:"bold",position:"relative",top:"45%"},style:{position:"absolute",backgroundColor:"#ffffff",opacity:.5,textAlign:"center"}},tooltip:{enabled:!0,animation:g,borderRadius:3,dateTimeLabelFormats:{millisecond:"%A, %e %b, %H:%M:%S.%L",second:"%A, %e %b, %H:%M:%S",
minute:"%A, %e %b, %H:%M",hour:"%A, %e %b, %H:%M",day:"%A, %e %b %Y",week:"Week from %A, %e %b %Y",month:"%B %Y",year:"%Y"},footerFormat:"",headerShape:"callout",hideDelay:500,padding:8,shape:"callout",shared:!1,snap:b?25:10,headerFormat:'<span style="font-size: 0.8em">{point.key}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.y}</b><br/>',backgroundColor:"#ffffff",borderWidth:void 0,shadow:!0,stickOnContact:!1,style:{color:"#333333",cursor:"default",
fontSize:"0.8em"},useHTML:!1},credits:{enabled:!0,href:"https://www.highcharts.com?credits",position:{align:"right",x:-10,verticalAlign:"bottom",y:-5},style:{cursor:"pointer",color:"#999999",fontSize:"0.6em"},text:"Highcharts.com"}};d.chart.styledMode=!1;"";const u=new y(d.time);a={defaultOptions:d,defaultTime:u,getOptions:function(){return d},setOptions:function(a){e(!0,d,a);if(a.time||a.global)f.time?f.time.update(e(d.global,d.time,a.global,a.time)):f.time=u;return d}};"";return a});k(a,"Core/Templating.js",
[a["Core/Defaults.js"],a["Core/Utilities.js"]],function(a,c){function f(a="",b,c){const d=/\{([a-zA-Z0-9:\.,;\-\/<>%_@"'= #\(\)]+)\}/g,h=/\(([a-zA-Z0-9:\.,;\-\/<>%_@"'= ]+)\)/g,e=[],l=/f$/,n=/\.([0-9])/,p=g.lang,u=c&&c.time||m,x=c&&c.numberFormatter||k,y=(a="")=>{let c;return"true"===a?!0:"false"===a?!1:(c=Number(a)).toString()===a?c:v(a,b)};let t,q,E=0,H;for(;null!==(t=d.exec(a));){const c=h.exec(t[1]);c&&(t=c,H=!0);q&&q.isBlock||(q={ctx:b,expression:t[1],find:t[0],isBlock:"#"===t[1].charAt(0),start:t.index,
startInner:t.index+t[0].length,length:t[0].length});var B=t[1].split(" ")[0].replace("#","");z[B]&&(q.isBlock&&B===q.fn&&E++,q.fn||(q.fn=B));B="else"===t[1];if(q.isBlock&&q.fn&&(t[1]===`/${q.fn}`||B))if(E)B||E--;else{var C=q.startInner;C=a.substr(C,t.index-C);void 0===q.body?(q.body=C,q.startInner=t.index+t[0].length):q.elseBody=C;q.find+=C+t[0];B||(e.push(q),q=void 0)}else q.isBlock||e.push(q);if(c&&(null===q||void 0===q||!q.isBlock))break}e.forEach(c=>{const {body:d,elseBody:h,expression:e,fn:k}=
c;var g;if(k){var m=[c],w=e.split(" ");for(g=z[k].length;g--;)m.unshift(y(w[g+1]));g=z[k].apply(b,m);c.isBlock&&"boolean"===typeof g&&(g=f(g?d:h,b))}else m=e.split(":"),g=y(m.shift()||""),m.length&&"number"===typeof g&&(m=m.join(":"),l.test(m)?(w=parseInt((m.match(n)||["","-1"])[1],10),null!==g&&(g=x(g,w,p.decimalPoint,-1<m.indexOf(",")?p.thousandsSep:""))):g=u.dateFormat(m,g));a=a.replace(c.find,D(g,""))});return H?f(a,b,c):a}function k(a,b,c,e){a=+a||0;b=+b;const h=g.lang;var l=(a.toString().split(".")[1]||
"").split("e")[0].length;const f=a.toString().split("e"),k=b;if(-1===b)b=Math.min(l,20);else if(!d(b))b=2;else if(b&&f[1]&&0>f[1]){var n=b+ +f[1];0<=n?(f[0]=(+f[0]).toExponential(n).split("e")[0],b=n):(f[0]=f[0].split(".")[0]||0,a=20>b?(f[0]*Math.pow(10,f[1])).toFixed(b):0,f[1]=0)}n=(Math.abs(f[1]?f[0]:a)+Math.pow(10,-Math.max(b,l)-1)).toFixed(b);l=String(p(n));const m=3<l.length?l.length%3:0;c=D(c,h.decimalPoint);e=D(e,h.thousandsSep);a=(0>a?"-":"")+(m?l.substr(0,m)+e:"");a=0>+f[1]&&!k?"0":a+l.substr(m).replace(/(\d{3})(?=\d)/g,
"$1"+e);b&&(a+=c+n.slice(-b));f[1]&&0!==+a&&(a+="e"+f[1]);return a}const {defaultOptions:g,defaultTime:m}=a,{extend:b,getNestedProperty:v,isArray:e,isNumber:d,isObject:u,pick:D,pInt:p}=c,z={add:(a,b)=>a+b,divide:(a,b)=>0!==b?a/b:"",eq:(a,b)=>a==b,each:function(a){const c=arguments[arguments.length-1];return e(a)?a.map((d,h)=>f(c.body,b(u(d)?d:{"@this":d},{"@index":h,"@first":0===h,"@last":h===a.length-1}))).join(""):!1},ge:(a,b)=>a>=b,gt:(a,b)=>a>b,"if":a=>!!a,le:(a,b)=>a<=b,lt:(a,b)=>a<b,multiply:(a,
b)=>a*b,ne:(a,b)=>a!=b,subtract:(a,b)=>a-b,unless:a=>!a};return{dateFormat:function(a,b,c){return m.dateFormat(a,b,c)},format:f,helpers:z,numberFormat:k}});k(a,"Dashboards/Components/KPIComponent.js",[a["Core/Renderer/HTML/AST.js"],a["Dashboards/Components/Component.js"],a["Core/Templating.js"],a["Core/Utilities.js"]],function(a,c,f,k){var g=this&&this.__awaiter||function(a,b,c,d){function h(a){return a instanceof c?a:new c(function(b){b(a)})}return new (c||(c=Promise))(function(c,e){function f(a){try{g(d.next(a))}catch(t){e(t)}}
function l(a){try{g(d["throw"](a))}catch(t){e(t)}}function g(a){a.done?c(a.value):h(a.value).then(f,l)}g((d=d.apply(a,b||[])).next())})};const {format:m}=f,{createElement:b,css:v,defined:e,getStyle:d,isArray:u,isNumber:x,merge:p,diffObjects:z}=k;class n extends c{static fromJSON(a,b){a=a.options;const c=a.chartOptions&&JSON.parse(a.chartOptions),d=JSON.parse(a.subtitle||"{}"),e=a.title&&JSON.parse(a.title);return new n(b,p(a,{chartOptions:c,title:e,subtitle:d}))}constructor(a,d){d=p(n.defaultOptions,
d);super(a,d);this.options=d;this.type="KPI";this.sync=new c.Sync(this,this.syncHandlers);this.value=b("span",{className:`${c.defaultOptions.className}-kpi-value`},{},this.contentElement);this.subtitle=b("span",{className:this.getSubtitleClassName()},{},this.contentElement);this.options.chartOptions&&(this.chartContainer=b("div",{className:`${c.defaultOptions.className}-kpi-chart-container`},{},this.contentElement))}load(){super.load();this.contentElement.style.display="flex";this.contentElement.style.flexDirection=
"column";this.parentElement.appendChild(this.element);this.updateElements();return this}resize(a,b){super.resize(a,b);!this.updatingSize&&this.dimensions.width&&this.dimensions.height&&this.updateSize(this.dimensions.width,this.dimensions.height);this.chart&&this.chart.reflow();this.updatingSize=!1;return this}updateTitleSize(a,b){this.titleElement&&(this.titleElement.style.fontSize=this.getFontSize(a,b,.08*(this.chart?1:1.7)))}getFontSize(a,b,c){return Math.max(this.options.minFontSize,Math.round(c*
Math.min(a,b)))+"px"}updateSize(a,b){this.updateTitleSize(a,b);const c=this.chart?1:1.7;this.value.style.fontSize=this.getFontSize(a,b,.15*c*(this.options.title?.7:1));this.subtitle.style.fontSize=this.getFontSize(a,b,.08*c);this.updatingSize=!0;super.resize(Number(d(this.parentElement,"width")),Number(d(this.parentElement,"height")))}render(){super.render();const a=n.charter;a&&this.options.chartOptions&&!this.chart&&this.chartContainer?this.chart=a.chart(this.chartContainer,p(n.defaultChartOptions,
this.options.chartOptions)):this.chart&&!this.options.chartOptions&&"chartOptions"in this.options&&(this.chart.destroy(),this.chart=void 0);return this}redraw(){super.redraw();this.updateElements();return this}update(a){const b=Object.create(null,{update:{get:()=>super.update}});return g(this,void 0,void 0,function*(){yield b.update.call(this,a);a.chartOptions&&this.chart&&this.chart.update(a.chartOptions);this.redraw()})}updateElements(){const {style:b,subtitle:c,valueFormat:d,valueFormatter:f}=
this.options;this.options.title&&(this.setTitle(this.options.title),this.dimensions.width&&this.dimensions.height&&this.updateTitleSize(this.dimensions.width,this.dimensions.height));let g=this.options.value;if(e(g)){let b;x(g)&&(b=g);f?g=f.call(this,g):d?g=m(d,{value:g}):x(g)&&(g=g.toLocaleString());a.setElementHTML(this.value,g);a.setElementHTML(this.subtitle,this.getSubtitle());this.prevValue=b}b&&v(this.element,b);"object"===typeof c&&(c.style&&v(this.subtitle,c.style),this.subtitle.className=
this.getSubtitleClassName());this.chartContainer&&(this.chartContainer.style.flex=this.options.chartOptions?"1":"0");this.chart&&this.chart.reflow();this.value.style.color=this.getValueColor()}getSubtitle(){const {subtitle:a,value:b}=this.options;if("string"===typeof a)return a;if(a){if(x(this.prevValue)&&x(b)){const c=b-this.prevValue;let d;if(0<c)d='<span style="color:green">&#9650;</span> +';else if(0>c)d='<span style="color:red">&#9660;</span> ';else return this.subtitle.innerHTML;if("diff"===
a.type)return d+c.toLocaleString();if("diffpercent"===a.type)return d+m("{v:,.2f}%",{v:c/this.prevValue*100})}return a.text||""}return""}getSubtitleClassName(){const {subtitle:a}=this.options;return`${c.defaultOptions.className}-kpi-subtitle`+("object"===typeof a&&a.className||"")}getValueColor(){const {threshold:a,thresholdColors:b,value:c}=this.options;if(b&&a&&x(c)){if(u(a))for(let d=a.length-1;0<=d;d--){if(c>=a[d])return d+1<b.length?b[d+1]:b[b.length-1]}else if(c>=a)return b[1];return b[0]}return""}toJSON(){const a=
super.toJSON(),b=Object.assign(Object.assign({},a),{type:"KPI",options:Object.assign(Object.assign({},a.options),{type:"KPI",value:this.options.value,subtitle:JSON.stringify(this.options.subtitle),title:JSON.stringify(this.options.title),threshold:this.options.threshold,thresholdColors:this.options.thresholdColors,chartOptions:JSON.stringify(this.options.chartOptions),valueFormat:this.options.valueFormat})});this.emit({type:"toJSON",json:a});return b}getOptions(){return Object.assign(Object.assign({},
z(this.options,n.defaultOptions)),{type:"KPI"})}}n.defaultOptions=p(c.defaultOptions,{type:"KPI",className:[c.defaultOptions.className,`${c.defaultOptions.className}-kpi`].join(" "),minFontSize:20,thresholdColors:["#f45b5b","#90ed7d"]});n.defaultChartOptions={chart:{type:"spline",backgroundColor:"transparent"},title:{text:void 0},xAxis:{visible:!1},yAxis:{visible:!1,title:{text:null}},legend:{enabled:!1},credits:{enabled:!1},tooltip:{outside:!0},plotOptions:{series:{marker:{enabled:!1}}}};return n});
k(a,"Dashboards/Plugins/HighchartsPlugin.js",[a["Dashboards/Plugins/HighchartsComponent.js"],a["Dashboards/Components/KPIComponent.js"],a["Dashboards/Plugins/HighchartsSyncHandlers.js"]],function(a,c,f){return{custom:{connectHighcharts:function(f){a.charter=f;c.charter=f}},name:"Highcharts.DashboardsPlugin",onRegister:function(g){const {Sync:k,ComponentRegistry:m}=g;m.registerComponent("Highcharts",a);m.registerComponent("KPI",c);k.defaultHandlers=Object.assign(Object.assign({},k.defaultHandlers),
f)},onUnregister:function(a){const {Sync:c}=a;Object.keys(f).forEach(a=>{c.defaultHandlers[a]===f[a]&&delete c.defaultHandlers[a]})}}});k(a,"masters/modules/dashboards-plugin.src.js",[a["Dashboards/Plugins/DataGridPlugin.js"],a["Dashboards/Globals.js"],a["Dashboards/Plugins/HighchartsPlugin.js"]],function(a,c,f){c.DataGridPlugin=a;c.HighchartsPlugin=f;c.win.Highcharts&&(f.custom.connectHighcharts(c.win.Highcharts),c.PluginHandler.addPlugin(f));c.win.DataGrid&&(a.custom.connectDataGrid(c.win.DataGrid.DataGrid),
c.PluginHandler.addPlugin(a));return c})});//# sourceMappingURL=dashboards-plugin.js.map